First Chinese Version

diff --git a/trunk/src/plugins/collectd/etc/init.d/collectd b/trunk/src/plugins/collectd/etc/init.d/collectd
--- a/trunk/src/plugins/collectd/etc/init.d/collectd
+++ b/trunk/src/plugins/collectd/etc/init.d/collectd
@@ -57,29 +57,29 @@ fi
 function collectd_start() {
 	echo "Starting the openQRM collectd-plugin"
 	collectd_stop 1>/dev/null 2>&1
-   	export FORCE_INSTALL=true
-   	openqrm_install_os_dependency collectd
+	export FORCE_INSTALL=true
+	openqrm_install_os_dependency collectd
 	openqrm_chkconfig del collectd
 	collectd_stop 1>/dev/null 2>&1
 
-    # prepare collectd client config
-    mkdir -p $COLLECTD_DATA_DIR
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/collectd/etc/templates/openqrm-collectd.conf | \
-        sed -e "s/@@MODE@@/Server/g" |  \
-        sed -e "s#@@COLLECTD_DATA_DIR@@#$COLLECTD_DATA_DIR#g" |  \
-        sed -e "s#@@OPENQRM_HOSTNAME@@#$appliance_name#g" |  \
-        sed -e "s/@@OPENQRM_SERVER_IP_ADDRESS@@/$resource_openqrmserver/g" > $COLLECTD_CONF
+	# prepare collectd client config
+	mkdir -p $COLLECTD_DATA_DIR
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/collectd/etc/templates/openqrm-collectd.conf | \
+		sed -e "s/@@MODE@@/Server/g" |  \
+		sed -e "s#@@COLLECTD_DATA_DIR@@#$COLLECTD_DATA_DIR#g" |  \
+		sed -e "s#@@OPENQRM_HOSTNAME@@#$appliance_name#g" |  \
+		sed -e "s/@@OPENQRM_SERVER_IP_ADDRESS@@/$resource_openqrmserver/g" > $COLLECTD_CONF
 
-    # start collectd
-    if [ -x /usr/sbin/collectdmon ]; then
-        if ! /usr/sbin/collectdmon -P /var/run/collectdmon.pid -- -C $COLLECTD_CONF 1>/dev/null 2>&1; then
-            echo "ERROR: Could not start collectd"
-        fi
-    elif [ -x /usr/sbin/collectd ]; then
-        if ! /usr/sbin/collectd -C $COLLECTD_CONF; then
-            echo "ERROR: Could not start collectd"
-        fi
-    fi
+	# start collectd
+	if [ -x /usr/sbin/collectdmon ]; then
+		if ! /usr/sbin/collectdmon -P /var/run/collectdmon.pid -- -C $COLLECTD_CONF 1>/dev/null 2>&1; then
+			echo "ERROR: Could not start collectd"
+		fi
+	elif [ -x /usr/sbin/collectd ]; then
+		if ! /usr/sbin/collectd -C $COLLECTD_CONF; then
+			echo "ERROR: Could not start collectd"
+		fi
+	fi
 }
 
 
@@ -89,7 +89,7 @@ function collectd_stop() {
 		/etc/init.d/collectd stop
 	fi
 	kill `ps ax | grep collectd.conf | grep -v grep | awk {' print $1 '}` 2>/dev/null
-    # be sure it is gone
+	# be sure it is gone
 	kill -9 `ps ax | grep collectd.conf | grep -v grep | awk {' print $1 '}` 2>/dev/null
 }
 
diff --git a/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage b/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage
--- a/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage
+++ b/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage
@@ -20,22 +20,30 @@
 # this script automatically manages iscsi
 OPENQRM_SERVER_BASE_DIR=$(dirname $0)/../../../..
 OPENQRM_SERVER_BASE_DIR=$(pushd $OPENQRM_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
+. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/include/openqrm-plugin-iscsi-storage-functions
 OPENQRM_POSTENCODE="$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-postencode"
 if [ -f /var/openqrm/openqrm-resource.conf ]; then
 	. /var/openqrm/openqrm-resource.conf
 	OPENQRM_SERVER_IP=$resource_openqrmserver
+	OPENQRM_EXEC_PORT=$resource_execdport
 elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
-	OPENQRM_SERVER_IP=localhost
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
+	openqrm_server_get_config
+	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
 	resource_id=0
 	resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
-    openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
+	openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
 fi
 export LANG=C
+# how long to wait for the volume authentication, each loop is 5 secs
+MAX_VOLUME_AUTHENTICATION_LOOP=30
+export MAX_VOLUME_AUTHENTICATION_LOOP
+
 # define wget to use with https
 if [ "$openqrm_web_protocol" == "https" ]; then
-    WGET_NO_CERT_CHECK="--no-check-certificate"
+	WGET_NO_CERT_CHECK="--no-check-certificate"
 fi
 # let only root run this script
 WHOAMI=`whoami`
@@ -125,7 +133,11 @@ case "$ISCSI_COMMAND" in
 	add)
 		if [ "$ISCSI_IMAGE_SIZE" == "" ]; then
 			ISCSI_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
-			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
+		fi
+
+		if [ -f "$ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME" ]; then
+			openqrm_post_event 0 "add" 3 "iscsi-storage" "Volume $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME already exist."
+			exit 1
 		fi
 		export ISCSI_IMAGE_SIZE
 		echo -n "Creating ISCSI Lun for image $ISCSI_IMAGE_NAME"
@@ -153,32 +165,31 @@ case "$ISCSI_COMMAND" in
 
 	snap)
 		if [ "$ISCSI_IMAGE_SNAPSHOT_NAME" == "" ]; then
-			echo "ERROR: Please give a name for the snapshot using the -s cmdline parmeter"
-			echo
+			openqrm_post_event 0 "snap" 3 "iscsi-storage" "No snapshot name given. Please use the -s cmdline parameter."
 			iscsi_storage_usage
 		fi
-		
+
 		# check that source fs-images exist
 		if [ ! -f $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME ]; then
-			echo "ERROR: Could not find source image $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME on the storage-server"
+			openqrm_post_event 0 "snap" 3 "iscsi-storage" "Could not find source volume $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME."
 			exit 1
 		fi
 		if [ ! -f $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME.conf ]; then
-			echo "ERROR: Could not find source image $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME config file"
-            exit 1
-        else
-            . $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME.conf
-            ISCSI_ORIGINAL_IMAGE_SIZE=$LUN_SIZE
-            if [ "$ISCSI_ORIGINAL_IMAGE_SIZE" == "" ]; then
-                echo "ERROR: Could not find out original image size ! Skipping snapshot."
-                exit 1
-            fi
+			openqrm_post_event 0 "snap" 3 "iscsi-storage" "Could not find source volume config $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME.conf."
+			exit 1
+		else
+			. $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME.conf
+			ISCSI_ORIGINAL_IMAGE_SIZE=$LUN_SIZE
+			if [ "$ISCSI_ORIGINAL_IMAGE_SIZE" == "" ]; then
+				openqrm_post_event 0 "snap" 3 "iscsi-storage" "Could not find out original image size of $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME."
+				exit 1
+			fi
 		fi
 		echo -n "Creating snapshot from image $ISCSI_IMAGE_NAME -> $ISCSI_IMAGE_SNAPSHOT_NAME size $ISCSI_ORIGINAL_IMAGE_SIZE"
 		mkdir -p $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY
 		cp -a $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_SNAPSHOT_NAME
 		export ISCSI_IMAGE_NAME=$ISCSI_IMAGE_SNAPSHOT_NAME
-        export ISCSI_IMAGE_SIZE=$ISCSI_ORIGINAL_IMAGE_SIZE
+		export ISCSI_IMAGE_SIZE=$ISCSI_ORIGINAL_IMAGE_SIZE
 		iscsi_storage_lock aquire
 		manage_iscsi add snap $ISCSI_IMAGE_PASSWORD
 		iscsi_storage_lock release
@@ -190,12 +201,29 @@ case "$ISCSI_COMMAND" in
 
 	auth)
 		echo -n "Authenticating ISCSI Lun for image rootdevice $ISCSI_IMAGE_ROOTDEVICE"
+		# this is just for starting auth, make sure the device is there, otherwise wait
+		if [ "$ISCSI_OPENQRM_USERNAME" != "" ] && [ "$ISCSI_OPENQRM_PASSWORD" != "" ] && [ "$ISCSI_IMAGE_NAME" != "" ]; then
+			MAX_AUTH_LOOP=0
+			while (true); do
+				if [ -e "$ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME" ]; then
+					break
+				fi
+				sleep 5
+				if [ "$MAX_AUTH_LOOP" == "$MAX_VOLUME_AUTHENTICATION_LOOP" ]; then
+					openqrm_post_event 0 "auth" 3 "iscsi-storage" "Volume $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME does not exist. Cannot auth."
+					exit 1
+				fi
+				MAX_AUTH_LOOP=$(( MAX_AUTH_LOOP + 1 ))
+			done
+		fi
 		iscsi_storage_lock aquire
 		manage_iscsi auth $ISCSI_IMAGE_PASSWORD
 		iscsi_storage_lock release
 		# in case we have a username + password post the updated list to the openQRM-server
-		if [ "$ISCSI_OPENQRM_USERNAME" != "" ] && [ "$ISCSI_OPENQRM_PASSWORD" != "" ]; then
-			$0 post_luns -u $ISCSI_OPENQRM_USERNAME -p $ISCSI_OPENQRM_PASSWORD
+		if [ "$ISCSI_OPENQRM_USERNAME" != "" ] && [ "$ISCSI_OPENQRM_PASSWORD" != "" ] && [ "$ISCSI_IMAGE_NAME" != "" ]; then
+			if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=auth_finished&iscsi_image_name=$ISCSI_IMAGE_NAME"; then
+				openqrm_post_event 0 "auth" 3 "iscsi-storage" "Could not remove the storage-auth-blocker for volume Volume $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME."
+			fi
 		fi
 		;;
 
@@ -205,7 +233,7 @@ case "$ISCSI_COMMAND" in
 	post_luns)
 		echo "Posting current iscsi-luns to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.iscsi.stat
-        # take care to only post "our" iscsi luns and not the ones from e.g lvm-iscsi-storage
+		# take care to only post "our" iscsi luns and not the ones from e.g lvm-iscsi-storage
 		#cat $IETDCONF | grep -v '#' | grep Lun | grep $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY | cut -d',' -f1 | awk {' print $2" "$3 '} | sed -e "s/Path=//g" > $STORAGE_STATUS_TMP
 		> $STORAGE_STATUS_TMP
 		OLD_IFS=$IFS
@@ -215,26 +243,25 @@ IFS='
 			LUN=`echo $LUN_STR | awk {'print $2 '}`
 			IMAGE_NAME=`echo $LUN_STR | awk {'print $3 '}`
 			IMAGE_NAME=`basename $IMAGE_NAME | cut -d',' -f1`
-            # get the size from the config file
-            if [ ! -f $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME.conf ]; then
-                echo "WARNING: Could not find source image $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME config file"
-                IMAGE_SIZE=0
-            else
-                . $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME.conf
-                IMAGE_SIZE=$LUN_SIZE
-                if [ "$IMAGE_SIZE" == "" ]; then
-                    echo "WARNING: Could not find source image $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME config file"
-                    IMAGE_SIZE=0
-                fi
-                unset LUN_SIZE
-            fi
+			# get the size from the config file
+			if [ ! -f $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME.conf ]; then
+				#echo "WARNING: Could not find source image $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME config file"
+				IMAGE_SIZE=0
+			else
+				. $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME.conf
+				IMAGE_SIZE=$LUN_SIZE
+				if [ "$IMAGE_SIZE" == "" ]; then
+					#echo "WARNING: Could not find source image $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME config file"
+					IMAGE_SIZE=0
+				fi
+				unset LUN_SIZE
+			fi
 			echo "$LUN $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$IMAGE_NAME $IMAGE_SIZE""@" >> $STORAGE_STATUS_TMP
 		done
 		IFS=$OLD_IFS
-        sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
+		sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=get_storage; then
-			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!" | logger
+			openqrm_post_event 0 "post_luns" 3 "iscsi-storage" "Could not post the iscsi target status to openQRM at $OPENQRM_SERVER_IP."
 		fi
 		rm -f $STORAGE_STATUS_TMP
 		rm -f $STORAGE_STATUS_TMP.post
@@ -255,8 +282,7 @@ IFS='
 		done
 		IFS=$OLD_IFS
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=get_ident; then
-			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!" | logger
+			openqrm_post_event 0 "post_identifier" 3 "iscsi-storage" "Could not post the iscsi target identifier to openQRM at $OPENQRM_SERVER_IP."
 		fi
 		rm -f $STORAGE_STATUS_TMP
 		rm -f $STORAGE_STATUS_TMP.post
diff --git a/trunk/src/plugins/kvm-storage/bin/openqrm-kvm-storage b/trunk/src/plugins/kvm-storage/bin/openqrm-kvm-storage
--- a/trunk/src/plugins/kvm-storage/bin/openqrm-kvm-storage
+++ b/trunk/src/plugins/kvm-storage/bin/openqrm-kvm-storage
@@ -33,19 +33,19 @@ elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
 	resource_id=0
 	resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
-    openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
+	openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
 fi
 export LANG=C
 LINEBR='
 '
+# how long to wait for the volume authentication, each loop is 5 secs
+MAX_VOLUME_AUTHENTICATION_LOOP=30
+export MAX_VOLUME_AUTHENTICATION_LOOP
+
 # define wget to use with https
 if [ "$openqrm_web_protocol" == "https" ]; then
-    WGET_NO_CERT_CHECK="--no-check-certificate"
+	WGET_NO_CERT_CHECK="--no-check-certificate"
 fi
-
-# using the resource_id as the shelf-id
-AOE_SHELF=$resource_id
-export AOE_SHELF
 
 # let only root run this script
 WHOAMI=`whoami`
@@ -156,7 +156,8 @@ fi
 if [ "$LVM_COMMAND" != "list" ] && [ "$LVM_COMMAND" != "post_vg" ] && [ "$LVM_COMMAND" != "post_identifier" ] && [ "$LVM_COMMAND" != "auth" ]; then
 	# check if volume group exists
 	if ! `vgdisplay | grep $LVM_STORAGE_SERVER_VOLUME_GROUP 1>/dev/null`; then
-		echo "ERROR: Could not find volume-group $LVM_STORAGE_SERVER_VOLUME_GROUP on the storage-server"
+		openqrm_post_event 0 "check" 2 "openqrm-kvm-storage" "Could not find volume group $LVM_STORAGE_SERVER_VOLUME_GROUP on the storage-server!"
+		echo "ERROR: Could not find volume-group $LVM_STORAGE_SERVER_VOLUME_GROUP on the storage-server!"
 		exit 1
 	fi
 fi
@@ -164,116 +165,129 @@ fi
 case "$LVM_COMMAND" in 
 
 	add)
-	
 		if [ "$LVM_IMAGE_SIZE" == "" ]; then
 			LVM_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
-			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
 		fi
 		export LVM_IMAGE_SIZE
-		echo -n "Creating logical volume $LVM_IMAGE_NAME size $LVM_IMAGE_SIZE MB using volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
-        kvm_storage_lock aquire
+		# check if already exists
+		if [ -e /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME ]; then
+			openqrm_post_event 0 "add" 3 "openqrm-kvm-storage" "Volume $LVM_IMAGE_NAME already exists"
+			exit 1
+		fi
+		echo "Creating logical volume $LVM_IMAGE_NAME size $LVM_IMAGE_SIZE MB using volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
+		kvm_storage_lock aquire
 		lvcreate -L$LVM_IMAGE_SIZE -n$LVM_IMAGE_NAME $LVM_STORAGE_SERVER_VOLUME_GROUP
-        kvm_storage_lock release
-
+		kvm_storage_lock release
 		# in case we have a username + password post the updated list to the openQRM-server
 		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ]; then
 			$0 post_lv -u $LVM_OPENQRM_USERNAME -p $LVM_OPENQRM_PASSWORD -v $LVM_STORAGE_SERVER_VOLUME_GROUP
 		fi
-
+		openqrm_post_event 0 "add" 5 "openqrm-kvm-storage" "Created logical volume $LVM_IMAGE_NAME on volume group $LVM_STORAGE_SERVER_VOLUME_GROUP."
 		;;
 
 	remove)
-
-		echo -n "Removing logical volume $LVM_IMAGE_NAME on volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
-        kvm_storage_lock aquire
+		# check that no snapshots existing with this volume as the origin
+		if lvs | awk '{ print $5 }' | grep -w $LVM_IMAGE_NAME 1>/dev/null; then
+			openqrm_post_event 0 "remove" 3 "openqrm-kvm-storage" "Snapshot exist from volume /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME. Not removing!"
+			exit 1
+		fi
+		kvm_storage_lock aquire
 		lvchange -a n /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
 		lvremove -f /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
-        kvm_storage_lock release
+		kvm_storage_lock release
 		# in case we have a username + password post the updated list to the openQRM-server
 		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ]; then
 			$0 post_lv -u $LVM_OPENQRM_USERNAME -p $LVM_OPENQRM_PASSWORD -v $LVM_STORAGE_SERVER_VOLUME_GROUP
 		fi
-
+		openqrm_post_event 0 "remove" 5 "openqrm-kvm-storage" "Removed logical volume $LVM_IMAGE_NAME on volume group $LVM_STORAGE_SERVER_VOLUME_GROUP."
 		;;
 
 	snap)
 		if [ "$LVM_IMAGE_SNAPSHOT_NAME" == "" ]; then
-			echo "ERROR: Please give a name for the snapshot using the -s cmdline parmeter"
-			echo
 			kvm_storage_usage
 		fi
 		if [ "$LVM_IMAGE_SIZE" == "" ]; then
 			LVM_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
-			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
 		fi
 		export LVM_IMAGE_SIZE
-		
 		# check that source fs-images exist
 		if ! `lvdisplay /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME 1>/dev/null`; then
-			echo "ERROR: Could not find /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME on the storage-server"
+			openqrm_post_event 0 "snap" 2 "openqrm-kvm-storage" "Could not find /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME on the storage-server!"
 			exit 1
 		fi
-		echo -n "Creating snapshot size $LVM_IMAGE_SIZE from logical volume $LVM_IMAGE_NAME -> $LVM_IMAGE_SNAPSHOT_NAME"
-        kvm_storage_lock aquire
+		kvm_storage_lock aquire
+		lvchange -ay /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
 		lvcreate --size $LVM_IMAGE_SIZE""m --snapshot --name $LVM_IMAGE_SNAPSHOT_NAME /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
-        kvm_storage_lock release
+		kvm_storage_lock release
 		# in case we have a username + password post the updated list to the openQRM-server
 		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ]; then
 			$0 post_lv -u $LVM_OPENQRM_USERNAME -p $LVM_OPENQRM_PASSWORD -v $LVM_STORAGE_SERVER_VOLUME_GROUP
 		fi
+		openqrm_post_event 0 "snap" 5 "openqrm-kvm-storage" "Created snapshot from logical volume $LVM_IMAGE_NAME -> $LVM_IMAGE_SNAPSHOT_NAME."
 		;;
 
 	auth)
-		echo "Authenticating $LVM_IMAGE_TYPE image $LVM_IMAGE_ROOTDEVICE to $LVM_IMAGE_AUTH"
+		# this is just for starting auth, make sure the device is there, otherwise wait
+		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ] && [ "$LVM_IMAGE_NAME" != "" ]; then
+			MAX_AUTH_LOOP=0
+			while (true); do
+				lvchange -ay $LVM_IMAGE_ROOTDEVICE
+				if [ -e "$LVM_IMAGE_ROOTDEVICE" ]; then
+					break
+				fi
+				sleep 5
+				if [ "$MAX_AUTH_LOOP" == "$MAX_VOLUME_AUTHENTICATION_LOOP" ]; then
+					openqrm_post_event 0 "auth" 2 "openqrm-kvm-storage" "Volume volume $LVM_IMAGE_ROOTDEVICE does not exist! Auth to $LVM_IMAGE_AUTH failed!"
+					exit 1
+				fi
+				MAX_AUTH_LOOP=$(( MAX_AUTH_LOOP + 1 ))
+			done
+			# if we have an image name send back to openQRM that storage auth finished to remvoe the storage-auth-blocker
+			if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$LVM_OPENQRM_USERNAME --http-password=$LVM_OPENQRM_PASSWORD "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/kvm-storage/kvm-storage-action.php?lvm_storage_command=auth_finished&kvm_storage_image_name=$LVM_IMAGE_NAME"; then
+				openqrm_post_event 0 "auth" 2 "openqrm-kvm-storage" "Could not remove auth-blocker for logical volume $LVM_IMAGE_NAME!"
+			fi
+		fi
 		;;
 
 	list)
 		lvm lvs
 		;;
 	post_vg)
-		echo "Posting current volume group status to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.vg.stat
 		vgs | grep -v VFree | sed -e "s/ \{1,\}//" > $STORAGE_STATUS_TMP
-        sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
+		sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$LVM_OPENQRM_USERNAME --http-password=$LVM_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/kvm-storage/kvm-storage-action.php?lvm_storage_command=get_storage; then
-			echo "ERROR: Could not post the volume group status to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post the volume group status to the openQRM-server at $resource_openqrmserver!" | logger
+			openqrm_post_event 0 "post_vg" 2 "openqrm-kvm-storage" "Could not post the volume group status to the openQRM-server at $OPENQRM_SERVER_IP!"
 		fi
 		rm -f $STORAGE_STATUS_TMP
 		rm -f $STORAGE_STATUS_TMP.post
 		;;
 	post_lv)
-		echo "Posting current $LVM_IMAGE_TYPE logic volume status to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.$LVM_STORAGE_SERVER_VOLUME_GROUP.lv.stat
 		> $STORAGE_STATUS_TMP
-        for LVOL in `lvs $LVM_STORAGE_SERVER_VOLUME_GROUP | grep -v LSize | sed -e "s/ \{1,\}//" | awk {' print $1 '}`; do
-            lvs $LVM_STORAGE_SERVER_VOLUME_GROUP/$LVOL | grep -v LSize | sed -e "s/ \{1,\}//" >> $STORAGE_STATUS_TMP
+		for LVOL in `lvs $LVM_STORAGE_SERVER_VOLUME_GROUP | grep -v LSize | sed -e "s/ \{1,\}//" | awk {' print $1 '}`; do
+			lvs $LVM_STORAGE_SERVER_VOLUME_GROUP/$LVOL | grep -v LSize | sed -e "s/ \{1,\}//" >> $STORAGE_STATUS_TMP
 		done
-        sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
+		sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$LVM_OPENQRM_USERNAME --http-password=$LVM_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/kvm-storage/kvm-storage-action.php?lvm_storage_command=get_storage; then
-			echo "ERROR: Could not post the logic volume status to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post the logic volume status to the openQRM-server at $resource_openqrmserver!" | logger
+			openqrm_post_event 0 "post_lv" 2 "openqrm-kvm-storage" "Could not post the logical volume status to the openQRM-server at $OPENQRM_SERVER_IP!"
 		fi
 		rm -f $STORAGE_STATUS_TMP
 		rm -f $STORAGE_STATUS_TMP.post
 		;;
 	post_identifier)
-		echo "Posting current $LVM_IMAGE_TYPE logical volume identifier to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.lv.kvm-lvm-deployment.ident
 		> $STORAGE_STATUS_TMP
-
 		for LVOL in `lvdisplay | grep "LV Name" | awk {' print $3 '}`; do
 			LVOL_SHORT=`basename $LVOL`
-            IMAGE_NAME=$LVOL_SHORT
-            VOLUME_GROUP=`echo $LVOL | cut -d'/' -f3`
-            echo "$IMAGE_NAME:/dev/$VOLUME_GROUP/$IMAGE_NAME"
-            echo "$IMAGE_NAME:/dev/$VOLUME_GROUP/$IMAGE_NAME" >> $STORAGE_STATUS_TMP
-		
-		done
+			IMAGE_NAME=$LVOL_SHORT
+			VOLUME_GROUP=`echo $LVOL | cut -d'/' -f3`
+			echo "$IMAGE_NAME:/dev/$VOLUME_GROUP/$IMAGE_NAME"
+			echo "$IMAGE_NAME:/dev/$VOLUME_GROUP/$IMAGE_NAME" >> $STORAGE_STATUS_TMP
 
+		done
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$LVM_OPENQRM_USERNAME --http-password=$LVM_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/kvm-storage/kvm-storage-action.php?lvm_storage_command=get_ident; then
-			echo "ERROR: Could not post the logic volume status to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post the logic volume status to the openQRM-server at $resource_openqrmserver!" | logger
+			openqrm_post_event 0 "post_identifier" 2 "openqrm-kvm-storage" "Could not post the logical volume identifier to the openQRM-server at $OPENQRM_SERVER_IP!"
 		fi
 		rm -f $STORAGE_STATUS_TMP
 		rm -f $STORAGE_STATUS_TMP.post
@@ -283,75 +297,67 @@ case "$LVM_COMMAND" in
 	resize)
 		if [ "$LVM_IMAGE_SIZE" == "" ]; then
 			LVM_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
-			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
 		fi
 		export LVM_IMAGE_SIZE
-		echo "Resizing logical volume $LVM_IMAGE_NAME + size $LVM_IMAGE_SIZE MB using volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
-        kvm_storage_lock aquire
-        lvresize -L +$LVM_IMAGE_SIZE /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME 2>&1 | logger
-        kvm_storage_lock release
+		kvm_storage_lock aquire
+		lvchange -ay /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+		lvresize -L +$LVM_IMAGE_SIZE /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME 2>&1 | logger
+		kvm_storage_lock release
 		# in case we have a username + password post the updated list to the openQRM-server
 		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ]; then
 			$0 post_lv -u $LVM_OPENQRM_USERNAME -p $LVM_OPENQRM_PASSWORD -v $LVM_STORAGE_SERVER_VOLUME_GROUP
 		fi
-
+		openqrm_post_event 0 "resize" 5 "openqrm-kvm-storage" "Resized logical volume $LVM_IMAGE_NAME + $LVM_IMAGE_SIZE MB on volume group $LVM_STORAGE_SERVER_VOLUME_GROUP."
 		;;
 
 
 	clone)
-        # cloning is similar to snapshots but since lvm cannot (yet) create snapshots
-        # from snapshots we have to dd the origin (which may be a snapshot) to a
-        # new lvol.
+		# cloning is similar to snapshots but since lvm cannot (yet) create snapshots
+		# from snapshots we have to dd the origin (which may be a snapshot) to a
+		# new lvol.
 		if [ "$LVM_IMAGE_SNAPSHOT_NAME" == "" ]; then
-			echo "ERROR: Please give a name for the clone using the -s cmdline parmeter"
-			echo
 			kvm_storage_usage
 		fi
 		if [ "$LVM_IMAGE_SIZE" == "" ]; then
 			LVM_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
-			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
 		fi
 		export LVM_IMAGE_SIZE
-		echo "Cloning logical volume $LVM_IMAGE_NAME to $LVM_IMAGE_SNAPSHOT_NAME size $LVM_IMAGE_SIZE MB volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
-
-        # re-run in background via screen
-        if [ "$RUN_IN_BACKGROUND" != "true" ]; then
-            if [ -x /usr/bin/screen.real ]; then
-                RUNSCREEN="/usr/bin/screen.real"
-            else
-                RUNSCREEN=`which screen`
-            fi
-            export RUN_IN_BACKGROUND=true
-            SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
-            $RUNSCREEN -dmS $SCREEN_NAME $FULL_COMMANDLINE
-            exit
-        fi
-
-        kvm_storage_lock aquire
-		if ! lvcreate -L$LVM_IMAGE_SIZE -n$LVM_IMAGE_SNAPSHOT_NAME $LVM_STORAGE_SERVER_VOLUME_GROUP; then
-            echo "ERROR: Cloud not create target logical volume $LVM_IMAGE_SNAPSHOT_NAME !"
-            echo "ERROR: Cloud not create target logical volume $LVM_IMAGE_SNAPSHOT_NAME !" | logger
-            exit 1
-        fi
-        # copy content
-        echo "Running : dd if=/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME of=/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_SNAPSHOT_NAME bs=1M" | logger
-        kvm_storage_lock release
-        dd if=/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME of=/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_SNAPSHOT_NAME bs=1M
-
-        # here we notify openQRM that cloning has finished
-		# in case we have a username + password post the updated list to the openQRM-server
-        # and notify openQRM that cloning has finished
-		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ]; then
-            CLONE_FINISHED="$LVM_IMAGE_SNAPSHOT_NAME.clone"
-            touch $CLONE_FINISHED
-            if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$LVM_OPENQRM_USERNAME --http-password=$LVM_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $CLONE_FINISHED` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/kvm-storage/kvm-storage-action.php?lvm_storage_command=clone_finished; then
-                echo "ERROR: Could not post clone-finished status to the openQRM-server at $resource_openqrmserver!"
-                echo "ERROR: Could not post clone-finished status to the openQRM-server at $resource_openqrmserver!" | logger
-            fi
-            # post lv
-			$0 post_lv -u $LVM_OPENQRM_USERNAME -p $LVM_OPENQRM_PASSWORD -v $LVM_STORAGE_SERVER_VOLUME_GROUP
+		# re-run in background via screen
+		if [ "$RUN_IN_BACKGROUND" != "true" ]; then
+			if [ -x /usr/bin/screen.real ]; then
+				RUNSCREEN="/usr/bin/screen.real"
+			else
+				RUNSCREEN=`which screen`
+			fi
+			export RUN_IN_BACKGROUND=true
+			SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
+			$RUNSCREEN -dmS $SCREEN_NAME $FULL_COMMANDLINE
+			exit
 		fi
 
+		kvm_storage_lock aquire
+		if ! lvcreate -L$LVM_IMAGE_SIZE -n$LVM_IMAGE_SNAPSHOT_NAME $LVM_STORAGE_SERVER_VOLUME_GROUP; then
+			kvm_storage_lock release
+			openqrm_post_event 0 "clone" 2 "openqrm-kvm-storage" "Could not create target logical volume $LVM_IMAGE_SNAPSHOT_NAME!"
+			exit 1
+		fi
+		# copy content
+		kvm_storage_lock release
+		lvchange -ay /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+		dd if=/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME of=/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_SNAPSHOT_NAME bs=1M
+		# here we notify openQRM that cloning has finished
+		# in case we have a username + password post the updated list to the openQRM-server
+		# and notify openQRM that cloning has finished
+		if [ "$LVM_OPENQRM_USERNAME" != "" ] && [ "$LVM_OPENQRM_PASSWORD" != "" ]; then
+			CLONE_FINISHED="$LVM_IMAGE_SNAPSHOT_NAME.clone"
+			touch $CLONE_FINISHED
+			if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$LVM_OPENQRM_USERNAME --http-password=$LVM_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $CLONE_FINISHED` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/kvm-storage/kvm-storage-action.php?lvm_storage_command=clone_finished; then
+				openqrm_post_event 0 "clone" 2 "openqrm-kvm-storage" "Could not post clone-finished status to the openQRM-server at $OPENQRM_SERVER_IP!"
+			fi
+			# post lv
+			$0 post_lv -u $LVM_OPENQRM_USERNAME -p $LVM_OPENQRM_PASSWORD -v $LVM_STORAGE_SERVER_VOLUME_GROUP
+		fi
+		openqrm_post_event 0 "clone" 5 "openqrm-kvm-storage" "Cloned logical volume $LVM_IMAGE_NAME to $LVM_IMAGE_SNAPSHOT_NAME on volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
 		;;
 
 
diff --git a/trunk/src/plugins/kvm-storage/etc/init.d/kvm-storage b/trunk/src/plugins/kvm-storage/etc/init.d/kvm-storage
--- a/trunk/src/plugins/kvm-storage/etc/init.d/kvm-storage
+++ b/trunk/src/plugins/kvm-storage/etc/init.d/kvm-storage
@@ -36,6 +36,19 @@ elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 fi
 OPENQRM_VM_DIR="/var/lib/kvm-storage/openqrm/"
 export OPENQRM_VM_DIR
+OPENQRM_VM_MONITOR_DIR="/var/run/openqrm/kvm-storage"
+# define wget to use with https
+if [ "$openqrm_web_protocol" == "https" ]; then
+	WGET="wget -q --no-check-certificate"
+else
+	WGET="wget -q"
+fi
+# which screen binary to use
+if [ -x /usr/bin/screen.real ]; then
+	RUNSCREEN="/usr/bin/screen.real"
+else
+	RUNSCREEN=`which screen`
+fi
 
 # do not start on the intitrd
 if [ -f /etc/initrd-devices.conf ]; then
@@ -45,74 +58,144 @@ fi
 
 function kvm_start() {
 	echo "Starting the openQRM kvm-storage-plugin"
-   	export FORCE_INSTALL=true
-   	openqrm_install_os_dependency screen
+	 # first check if this is a kvm host
+	if ! which kvm 1>/dev/null; then
+		if ! which qemu-kvm 1>/dev/null; then
+			# maybe it is centos and not in the path
+			if [ ! -x /usr/libexec/qemu-kvm ]; then
+				exit 0
+			fi
+		fi
+	fi
+	# check that bridging is enabled, if not this may is not a kvm host
+	if ! which brctl 1>/dev/null; then
+		exit 0
+	fi
+	# otherwise we want to prepare the host a bit
+	export FORCE_INSTALL=true
+	openqrm_install_os_dependency screen
 
 	# preparing the nic-bios in case the openQRM server itself is the kvm-host
 	if [ ! -d /usr/share/kvm/ ]; then
 		mkdir -p /usr/share/kvm
 	fi
-    if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz ]; then
-        if [ -f /usr/share/kvm/pxe-e1000.bin ] && [ ! -f /usr/share/kvm/pxe-e1000.bin.openqrm-backup ]; then
-            cp -f /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-e1000.bin.openqrm-backup
-        fi
-        if [ -f /usr/share/kvm/pxe-rtl8139.bin ] && [ ! -f /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup ]; then
-            cp -f /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup
-        fi
-        if [ -f /usr/share/kvm/pxe-virtio.bin ] && [ ! -f /usr/share/kvm/pxe-virtio.bin.openqrm-backup ]; then
-            cp -f /usr/share/kvm/pxe-virtio.bin /usr/share/kvm/pxe-virtio.bin.openqrm-backup
-        fi
-        tar -C /usr/share/kvm/ -xzf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz
-        chown root:root /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-virtio.bin
-    fi
+	if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz ]; then
+		if [ -f /usr/share/kvm/pxe-e1000.bin ] && [ ! -f /usr/share/kvm/pxe-e1000.bin.openqrm-backup ]; then
+			cp -f /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-e1000.bin.openqrm-backup
+		fi
+		if [ -f /usr/share/kvm/pxe-rtl8139.bin ] && [ ! -f /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup ]; then
+			cp -f /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup
+		fi
+		if [ -f /usr/share/kvm/pxe-virtio.bin ] && [ ! -f /usr/share/kvm/pxe-virtio.bin.openqrm-backup ]; then
+			cp -f /usr/share/kvm/pxe-virtio.bin /usr/share/kvm/pxe-virtio.bin.openqrm-backup
+		fi
+		tar -C /usr/share/kvm/ -xzf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz
+		chown root:root /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-virtio.bin
+	fi
 
 	# be sure to have the tun device
-	if [ ! -f /dev/tun ]; then
+	if [ ! -e /dev/tun ]; then
 		mknod /dev/tun c 10 200
 	fi
 	depmod -a
 	modprobe tun
+	# setting the kvm-ifup +kvm-ifdown script to the internal and external bridge
+	# internal
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net1
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net1
+	# external
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net5
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net5
+	# ifup/down scripts for openvswitch
+	# internal
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#0#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net1
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#0#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net1
+	# external
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#1#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#1#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#2#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#2#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#3#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#3#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#4#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net5
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#4#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net5
+	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/*
 
-	# check that bridging is enabled
-	if ! which brctl 1>/dev/null; then
-		kvm_storage_log kvm_start "ERROR: brctl is not installed! Please install bridge-utils."
-		exit 1
+	# make sure the kvm modules are loaded
+	modprobe kvm
+	if grep flags.*vmx /proc/cpuinfo 1>/dev/null; then modprobe kvm-intel; fi
+	if grep flags.*svm /proc/cpuinfo 1>/dev/null; then modprobe kvm-amd; fi
+
+	# start the vm status autostart
+	if [ -d "$OPENQRM_VM_DIR" ]; then
+		for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
+			VM_NAME=`dirname $VM_CONFIG`
+			VM_NAME=`basename $VM_NAME`
+			. $OPENQRM_VM_DIR/$VM_NAME/net1
+			if ps ax | grep -i "$KVM_VM_MAC_1" | grep -v grep | grep -i screen 1>/dev/null; then
+				echo "- VM $VM_NAME is running already, not auto-starting it ..."
+				continue
+			fi
+			# ask openQRM what to do
+			if ! $WGET -O $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$KVM_VM_MAC_1"; then
+				echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
+				continue
+			fi
+			unset appliance_state
+			unset image_rootdevice
+			. $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf
+			# is really active ?
+			if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
+				echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
+				lvchange -ay $image_rootdevice
+				sleep 2
+				# make sure the lvm device is active
+				if [ -e "$image_rootdevice" ]; then
+					echo "- auto-starting active VM $VM_NAME"
+					# make sure the rigth device is in the VM config
+					echo "KVM_VM_DISK_1=\"$image_rootdevice\"" > $OPENQRM_VM_DIR/$VM_NAME/disk1
+					$OPENQRM_VM_DIR/$VM_NAME/$VM_NAME.kvm
+				else
+					echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
+					continue
+				fi
+			else
+				# make sure the VM is not still attached to the disk
+				echo 'KVM_VM_DISK_1=""' > $OPENQRM_VM_DIR/$VM_NAME/disk1
+				# start the kvm-storage monitor
+				echo "- auto-starting idle VM $VM_NAME"
+			fi
+			# starting the monitor for active + idle
+			kill `ps ax | grep openqrm-kvm-storage-monitord | grep -v grep | grep -i $KVM_VM_MAC_1 | awk {' print $1 '}` 2>/dev/null
+			$RUNSCREEN -dmS $KVM_VM_MAC_1 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/sbin/openqrm-kvm-storage-monitord $KVM_VM_MAC_1
+		done
 	fi
-	if ! which kvm 1>/dev/null; then
-        if ! which qemu-kvm 1>/dev/null; then
-            kvm_storage_log kvm_start "ERROR: kvm is not installed! Please install kvm."
-            exit 1
-        fi
-    fi
-    # setting the kvm-ifup +kvm-ifdown script to the internal and external bridge
-    # internal
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_INTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_INTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown
-    # external
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_EXTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-ext
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_EXTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-ext
-    chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/*
-
-    # make sure the kvm modules are loaded
-    modprobe kvm
-    if grep flags.*vmx /proc/cpuinfo 1>/dev/null; then modprobe kvm-intel; fi
-    if grep flags.*svm /proc/cpuinfo 1>/dev/null; then modprobe kvm-amd; fi
-
-    # start the vm status autostart
-    if [ -d "$OPENQRM_VM_DIR" ]; then
-        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart`; do
-            VM_NAME=`dirname $VM_CONFIG`
-            VM_NAME=`basename $VM_NAME`
-            echo "- auto-starting VM $VM_NAME"
-            $OPENQRM_VM_DIR/$VM_NAME/$VM_NAME.kvm
-        done
-    fi
 
 }
 
 
 function kvm_stop() {
 	echo "Stopping the openQRM kvm-storage-plugin"
+	# by default we do not stop the active VMs, otherwise openqrm-client restart would restart VMs
+#	if [ -d "$OPENQRM_VM_DIR" ]; then
+#		for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
+#			VM_NAME=`dirname $VM_CONFIG`
+#			VM_NAME=`basename $VM_NAME`
+#			if [ -e "$OPENQRM_VM_MONITOR_DIR/kvm.$VM_NAME.mon" ]; then
+#				echo "- Stopping VM $VM_NAME"
+#				echo "system_powerdown" | socat stdio unix:$OPENQRM_VM_MONITOR_DIR/kvm.$VM_NAME.mon
+#			fi
+#		done
+#	fi
+
+
+
 
 }
 
diff --git a/trunk/src/plugins/kvm-storage/etc/init.d/openqrm-plugin-kvm-storage b/trunk/src/plugins/kvm-storage/etc/init.d/openqrm-plugin-kvm-storage
--- a/trunk/src/plugins/kvm-storage/etc/init.d/openqrm-plugin-kvm-storage
+++ b/trunk/src/plugins/kvm-storage/etc/init.d/openqrm-plugin-kvm-storage
@@ -24,9 +24,24 @@ OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $
 . $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/include/openqrm-plugin-kvm-storage-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/openqrm-plugin-kvm-storage.conf
+openqrm_server_get_config
+OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
 OPENQRM_VM_DIR="/var/lib/kvm-storage/openqrm/"
 export OPENQRM_VM_DIR
+OPENQRM_VM_MONITOR_DIR="/var/run/openqrm/kvm-storage"
 
+# define wget to use with https
+if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
+	WGET="wget -q --no-check-certificate"
+else
+	WGET="wget -q"
+fi
+# which screen binary to use
+if [ -x /usr/bin/screen.real ]; then
+	RUNSCREEN="/usr/bin/screen.real"
+else
+	RUNSCREEN=`which screen`
+fi
 
 LINE_IFS='
 '
@@ -35,15 +50,50 @@ function openqrm_plugin_kvm_storage_start() {
 	openqrm_plugin_kvm_storage_stop 1>/dev/null 2>&1
 	echo "Starting the openQRM kvm-storage-plugin"
 	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/kvm-storage/.running
-    # start the vm status autostart
-    if [ -d "$OPENQRM_VM_DIR" ]; then
-        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart`; do
-            VM_NAME=`dirname $VM_CONFIG`
-            VM_NAME=`basename $VM_NAME`
-            echo "- auto-starting VM $VM_NAME"
-            $OPENQRM_VM_DIR/$VM_NAME/$VM_NAME.kvm
-        done
-    fi
+	# start the vm status autostart
+	if [ -d "$OPENQRM_VM_DIR" ]; then
+		for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart.0 2>/dev/null`; do
+			VM_NAME=`dirname $VM_CONFIG`
+			VM_NAME=`basename $VM_NAME`
+			. $OPENQRM_VM_DIR/$VM_NAME/net1
+			if ps ax | grep -i "$KVM_VM_MAC_1" | grep -v grep | grep -i screen 1>/dev/null; then
+				echo "- VM $VM_NAME is running already, not auto-starting it ..."
+				continue
+			fi
+			# ask openQRM what to do
+			if ! $WGET -O $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$KVM_VM_MAC_1"; then
+				echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
+				continue
+			fi
+			unset appliance_state
+			unset image_rootdevice
+			. $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf
+			# is really active ?
+			if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
+				echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
+				lvchange -ay $image_rootdevice
+				sleep 2
+				# make sure the lvm device is active
+				if [ -e "$image_rootdevice" ]; then
+					echo "- auto-starting active VM $VM_NAME"
+					# make sure the rigth device is in the VM config
+					echo "KVM_VM_DISK_1=\"$image_rootdevice\"" > $OPENQRM_VM_DIR/$VM_NAME/disk1
+					$OPENQRM_VM_DIR/$VM_NAME/$VM_NAME.kvm
+				else
+					echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
+					continue
+				fi
+			else
+				# make sure the VM is not still attached to the disk
+				echo 'KVM_VM_DISK_1=""' > $OPENQRM_VM_DIR/$VM_NAME/disk1
+				# start the kvm-storage monitor
+				echo "- auto-starting idle VM $VM_NAME"
+			fi
+			# starting the monitor for active + idle
+			kill `ps ax | grep openqrm-kvm-storage-monitord | grep -v grep | grep -i $KVM_VM_MAC_1 | awk {' print $1 '}` 2>/dev/null
+			$RUNSCREEN -dmS $KVM_VM_MAC_1 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/sbin/openqrm-kvm-storage-monitord $KVM_VM_MAC_1
+		done
+	fi
 
 }
 
@@ -59,7 +109,7 @@ function openqrm_plugin_kvm_storage_uninstall() {
 	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
 		echo -n "kvm-storage: Please give a username to uninstall the plugin : "
 		read USERNAME
-		echo	
+		echo
 		echo -n "kvm-storage: Please give the password for user $USERNAME : "
 		read PASSWORD
 		echo
@@ -81,7 +131,7 @@ function openqrm_plugin_kvm_storage_init() {
 	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
 		echo -n "kvm-storage: Please give a username to init the plugin : "
 		read USERNAME
-		echo	
+		echo
 		echo -n "kvm-storage: Please give the password for user $USERNAME : "
 		read PASSWORD
 		echo
@@ -97,41 +147,61 @@ function openqrm_plugin_kvm_storage_init() {
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/boot-service-kvm-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-kvm-storage.tgz
 	# linking the image deployment parameters menu
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/image.kvm-lvm-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.kvm-lvm-deployment.php
-    # create storage dir for stat files
-    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/storage
-    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/storage
+	# create storage dir for stat files
+	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/storage
+	chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/storage
 
 	# preparing the nic-bios in case the openQRM server itself is the kvm-host
 	if [ ! -d /usr/share/kvm/ ]; then
 		mkdir -p /usr/share/kvm
 	fi
-    if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz ]; then
-        if [ -f /usr/share/kvm/pxe-e1000.bin ] && [ ! -f /usr/share/kvm/pxe-e1000.bin.openqrm-backup ]; then
-            cp -f /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-e1000.bin.openqrm-backup
-        fi
-        if [ -f /usr/share/kvm/pxe-rtl8139.bin ] && [ ! -f /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup ]; then
-            cp -f /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup
-        fi
-        if [ -f /usr/share/kvm/pxe-virtio.bin ] && [ ! -f /usr/share/kvm/pxe-virtio.bin.openqrm-backup ]; then
-            cp -f /usr/share/kvm/pxe-virtio.bin /usr/share/kvm/pxe-virtio.bin.openqrm-backup
-        fi
-        tar -C /usr/share/kvm/ -xzf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz
-        chown root:root /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-virtio.bin
-    fi
+	if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz ]; then
+		if [ -f /usr/share/kvm/pxe-e1000.bin ] && [ ! -f /usr/share/kvm/pxe-e1000.bin.openqrm-backup ]; then
+			cp -f /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-e1000.bin.openqrm-backup
+		fi
+		if [ -f /usr/share/kvm/pxe-rtl8139.bin ] && [ ! -f /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup ]; then
+			cp -f /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup
+		fi
+		if [ -f /usr/share/kvm/pxe-virtio.bin ] && [ ! -f /usr/share/kvm/pxe-virtio.bin.openqrm-backup ]; then
+			cp -f /usr/share/kvm/pxe-virtio.bin /usr/share/kvm/pxe-virtio.bin.openqrm-backup
+		fi
+		tar -C /usr/share/kvm/ -xzf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.1.tgz
+		chown root:root /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-virtio.bin
+	fi
 
-    # setting the kvm-ifup +kvm-ifdown script to the internal and external bridge
-    # internal
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_INTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_INTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown
-    # external
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_EXTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-ext
-    cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_STORAGE_BRIDGE@@/$OPENQRM_PLUGIN_KVM_EXTERNAL_BRIDGE/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-ext
-    chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/*
-    # create kvm-stat dir
-    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/kvm-stat
-    chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/kvm-stat
+	# setting the kvm-ifup +kvm-ifdown script to the internal and external bridge
+	# internal
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net1
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net1
+	# external
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifup-net5
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-kvm-ifdown-net5
 
-	
+	# ifup/down scripts for openvswitch
+	# internal
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#0#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net1
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET1/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#0#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net1
+	# external
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#1#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET2/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#1#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net2
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#2#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET3/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#2#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net3
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#3#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET4/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#3#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net4
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifup | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#4#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifup-net5
+	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/etc/templates/openqrm-ovs-kvm-storage-ifdown | sed -e "s/@@OPENQRM_PLUGIN_KVM_BRIDGE@@/$OPENQRM_PLUGIN_KVM_BRIDGE_NET5/g" | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | sed -e "s#@@OPENQRM_APP_NIC@@#4#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/openqrm-ovs-kvm-ifdown-net5
+	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/bin/*
+	# create kvm-stat dir
+	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/kvm-stat
+	chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm-storage/web/kvm-stat
+
+
 }
 
 USER=$2
diff --git a/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm b/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm
--- a/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm
+++ b/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm
@@ -19,19 +19,24 @@
 
 KVM=`which kvm`
 if [ "$KVM" == "" ]; then
-    KVM=`which qemu-kvm`
-    if [ "$KVM" == "" ]; then
-        echo "ERROR: kvm ist not installed on this system !" | logger
-        exit 1
-    fi
+	KVM=`which qemu-kvm`
+	if [ "$KVM" == "" ]; then
+		# maybe it is centos and not in the path
+		if [ -x /usr/libexec/qemu-kvm ]; then
+			KVM=/usr/libexec/qemu-kvm
+		else
+			echo "ERROR: kvm ist not installed on this system !" | logger
+			exit 1
+		fi
+	fi
 fi
 # which screen binary to use
 if [ -x /usr/bin/screen.real ]; then
-    RUNSCREEN="/usr/bin/screen.real"
+	RUNSCREEN="/usr/bin/screen.real"
 else
-    RUNSCREEN=`which screen`
+	RUNSCREEN=`which screen`
 fi
-
+mkdir -p /var/run/openqrm/kvm
 
 # source the component config files
 VM_CONF_DIR=`dirname $0`
@@ -52,11 +57,12 @@ VM_NAME=`basename $VM_CONF_DIR`
 . $VM_CONF_DIR/boot
 
 
+
 KVM_VM_DISK="$KVM_VM_DISK_1 $KVM_VM_DISK_2 $KVM_VM_DISK_3 $KVM_VM_DISK_4"
 KVM_VM_NET="$KVM_VM_NET_1 $KVM_VM_NET_2 $KVM_VM_NET_3 $KVM_VM_NET_4 $KVM_VM_NET_5"
 
 echo "KVM vm $VM_NAME starting up ..." | logger
-$RUNSCREEN -dmS $KVM_VM_MAC_1 $KVM $KVM_VM_DISK -m $KVM_VM_RAM -smp $KVM_VM_CPUS $KVM_VM_BOOT $KVM_VM_NET -vnc $KVM_VM_VNC
+$RUNSCREEN -dmS $KVM_VM_MAC_1 $KVM $KVM_VM_DISK -m $KVM_VM_RAM -smp $KVM_VM_CPUS $KVM_VM_BOOT $KVM_VM_NET -vnc $KVM_VM_VNC -balloon virtio -monitor unix:/var/run/openqrm/kvm/kvm.$VM_NAME.mon,server,nowait
 
 
 
diff --git a/trunk/src/plugins/local-server/bin/openqrm-local-server b/trunk/src/plugins/local-server/bin/openqrm-local-server
--- a/trunk/src/plugins/local-server/bin/openqrm-local-server
+++ b/trunk/src/plugins/local-server/bin/openqrm-local-server
@@ -27,8 +27,8 @@ export LC_ALL=C
 
 
 function usage() {
-        echo "Usage : $0 integrate -u <user> -p <password> -q <ip-address-of-openQRM-server> [ -n <hostname> ] [-i <network-interface>] [-s <http/https>]"
-        echo "        $0 remove -u <user> -p <password> -q <ip-address-of-openQRM-server> [ -n <hostname> ] [-s <http/https>]"
+		echo "Usage : $0 integrate -u <user> -p <password> -q <ip-address-of-openQRM-server> [ -n <hostname> ] [-i <network-interface>] [-s <http/https>]"
+		echo "        $0 remove -u <user> -p <password> -q <ip-address-of-openQRM-server> [ -n <hostname> ] [-s <http/https>]"
 }
 
 
@@ -46,7 +46,7 @@ function openqrm_integrate_local_server() {
 		echo "ERROR: Interface $INTERFACE does not exists !"
 		exit 1
 	fi
-    # name
+	# name
 	if [ "$APPLIANCE_NAME" == "" ]; then
 		echo "Please give a name for this system"
 		echo -n "-> : "
@@ -55,58 +55,58 @@ function openqrm_integrate_local_server() {
 	local resource_id=-1
 	local resource_ip=`ifconfig $INTERFACE | grep "inet " | cut -d':' -f2 | cut -d' ' -f1`
 	local resource_mac=`ifconfig $INTERFACE | grep HWaddr| sed -e "s/.*HWaddr //g" | head -n1`
-    # define wget to use with https
-    if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
-        WGET_NO_CERT_CHECK="--no-check-certificate"
-    fi
+	# define wget to use with https
+	if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
+		WGET_NO_CERT_CHECK="--no-check-certificate"
+	fi
 	# remove whitespaces
 	resource_mac=`echo $resource_mac`
 	echo "Using $INTERFACE $resource_ip/$resource_mac"
-	
+
 	wget -q $WGET_NO_CERT_CHECK -O $OPENQRM_RESOURCE_PARAMETER_FILE "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
 	. $OPENQRM_RESOURCE_PARAMETER_FILE
-	
-	echo "Getting openqrm-client package"
-    # run default openqrm-client boot-service
-    KERNEL_ARCH=`uname -m`
-    if echo $KERNEL_ARCH | grep i.*86 1>/dev/null; then
-        # i386
-        OPENQRM_CLIENT_ARCH=i386
-    else
-        OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
-    fi
-    # find out the short distri name
-    if [ -f /etc/debian_version ]; then
-        # debian or ubuntu, try to find out without lsb-release which may not be installed
-        if grep -i ubuntu /etc/apt/sources.list 1>/dev/null; then
-            OPENQRM_SHORT_DISTRI_NAME="ubuntu"
-        else
-            OPENQRM_SHORT_DISTRI_NAME="debian"
-        fi
-    elif [ -f /etc/redhat-release ]; then
-        OPENQRM_SHORT_DISTRI_NAME="centos"
-    fi
 
-    cd /
-    if [ "$OPENQRM_SHORT_DISTRI_NAME" != "" ]; then
-        echo "Getting openqrm-client package $OPENQRM_SHORT_DISTRI_NAME/$OPENQRM_CLIENT_ARCH"
-        if ! wget -q -O openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.$OPENQRM_SHORT_DISTRI_NAME.$OPENQRM_CLIENT_ARCH.tgz"; then
-            rm -f openqrm-client.tgz
-            echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one fitting $OPENQRM_CLIENT_ARCH"
-            if ! wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.$OPENQRM_CLIENT_ARCH.tgz"; then
-                rm -f openqrm-client.tgz
-                echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
-                wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.tgz"
-            fi
-        fi
-    else
-        echo "Getting openqrm-client package $OPENQRM_CLIENT_ARCH"
-        if ! wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.$OPENQRM_CLIENT_ARCH.tgz"; then
-            rm -f openqrm-client.tgz
-            echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
-            wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.tgz"
-        fi
-    fi
+	echo "Getting openqrm-client package"
+	# run default openqrm-client boot-service
+	KERNEL_ARCH=`uname -m`
+	if echo $KERNEL_ARCH | grep i.*86 1>/dev/null; then
+		# i386
+		OPENQRM_CLIENT_ARCH=i386
+	else
+		OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
+	fi
+	# find out the short distri name
+	if [ -f /etc/debian_version ]; then
+		# debian or ubuntu, try to find out without lsb-release which may not be installed
+		if grep -i ubuntu /etc/apt/sources.list 1>/dev/null; then
+			OPENQRM_SHORT_DISTRI_NAME="ubuntu"
+		else
+			OPENQRM_SHORT_DISTRI_NAME="debian"
+		fi
+	elif [ -f /etc/redhat-release ]; then
+		OPENQRM_SHORT_DISTRI_NAME="centos"
+	fi
+
+	cd /
+	if [ "$OPENQRM_SHORT_DISTRI_NAME" != "" ]; then
+		echo "Getting openqrm-client package $OPENQRM_SHORT_DISTRI_NAME/$OPENQRM_CLIENT_ARCH"
+		if ! wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.$OPENQRM_SHORT_DISTRI_NAME.$OPENQRM_CLIENT_ARCH.tgz"; then
+			rm -f openqrm-client.tgz
+			echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one fitting $OPENQRM_CLIENT_ARCH"
+			if ! wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.$OPENQRM_CLIENT_ARCH.tgz"; then
+				rm -f openqrm-client.tgz
+				echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
+				wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.tgz"
+			fi
+		fi
+	else
+		echo "Getting openqrm-client package $OPENQRM_CLIENT_ARCH"
+		if ! wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.$OPENQRM_CLIENT_ARCH.tgz"; then
+			rm -f openqrm-client.tgz
+			echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
+			wget -q $WGET_NO_CERT_CHECK -O openqrm-client.tgz "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.tgz"
+		fi
+	fi
 
 	tar -xzf openqrm-client.tgz
 	rm -f openqrm-client.tgz
@@ -114,13 +114,13 @@ function openqrm_integrate_local_server() {
 	export OPENQRM_SERVER_BASE_DIR=$resource_basedir
 	. $resource_basedir/openqrm/include/openqrm-functions
 	openqrm_chkconfig add openqrm-client
-	
+
 	# gather some more details to create the appliance on the openQRM-server
 	local_server_root_device=`mount | grep ' / ' | awk {' print $1 '}`
 	local_server_root_device_type=`mount | grep ' / ' | awk {' print $5 '}`
 	local_server_kernel_version=`uname -r`
-    local_server_name=$APPLIANCE_NAME
-	
+	local_server_name=$APPLIANCE_NAME
+
 	# now we send the local-integration signal to create
 	# the local-server storage, image and appliance
 	if ! wget $WGET_NO_CERT_CHECK -O /dev/null -q --http-user=$USER --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/base/plugins/local-server/local-server-action.php?local_server_command=integrate&local_server_id=$resource_id&local_server_root_device=$local_server_root_device&local_server_root_device_type=$local_server_root_device_type&local_server_kernel_version=$local_server_kernel_version&local_server_name=$APPLIANCE_NAME"; then
@@ -130,33 +130,33 @@ function openqrm_integrate_local_server() {
 		openqrm_remove_local_server $USER $PASSWORD $OPENQRM_SERVER
 		return 1
 	fi
-    sleep 2
-	
-    # re-get parameters
-    rm -f $OPENQRM_RESOURCE_PARAMETER_FILE
+	sleep 2
+
+	# re-get parameters
+	rm -f $OPENQRM_RESOURCE_PARAMETER_FILE
 	wget -q $WGET_NO_CERT_CHECK -O $OPENQRM_RESOURCE_PARAMETER_FILE "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
-    # start the openQRM client late to get the new hostname from openQRM
+	# start the openQRM client late to get the new hostname from openQRM
 	$resource_basedir/openqrm/etc/init.d/openqrm-client start
-	
+
 }
 
 function openqrm_remove_local_server() {
 	echo "Removing system from openQRM-server at $OPENQRM_SERVER"
-    if [ ! -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
-        echo "NOTICE: This system is not integrated with openQRM"
-        exit 1
-    fi
+	if [ ! -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+		echo "NOTICE: This system is not integrated with openQRM"
+		exit 1
+	fi
 	. $OPENQRM_RESOURCE_PARAMETER_FILE
-    # name
+	# name
 	if [ "$APPLIANCE_NAME" == "" ]; then
 		echo "Please give the appliance name of this system"
 		echo -n "-> : "
 		read APPLIANCE_NAME
 	fi
-    # define wget to use with https
-    if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
-        WGET_NO_CERT_CHECK="--no-check-certificate"
-    fi
+	# define wget to use with https
+	if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
+		WGET_NO_CERT_CHECK="--no-check-certificate"
+	fi
 	# try to remove components from the local-server appliance
 	if ! wget $WGET_NO_CERT_CHECK -O /dev/null -q --http-user=$USER --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER/openqrm/base/plugins/local-server/local-server-action.php?local_server_command=remove&local_server_id=$resource_id&local_server_name=$APPLIANCE_NAME"; then
 		echo "WARNING: Could not remove the appliance resource$resouce_id from the openQRM-server!"
@@ -191,13 +191,13 @@ case "$1" in
 					;;
 				-p)
 					PASSWORD=$2
-					;;			
+					;;
 				-q)
 					OPENQRM_SERVER=$2
-					;;			
+					;;
 				-i)
 					INTERFACE=$2
-					;;			
+					;;
 				-n)
 					APPLIANCE_NAME=$2
 					;;
@@ -223,14 +223,14 @@ case "$1" in
 			exit 1
 		fi
 		if [ "$OPENQRM_WEB_PROTOCOL" == "" ]; then
-            OPENQRM_WEB_PROTOCOL=http
+			OPENQRM_WEB_PROTOCOL=http
 		fi
-        export USER
-        export PASSWORD
-        export OPENQRM_SERVER
-        export INTERFACE
-        export APPLIANCE_NAME
-        export OPENQRM_WEB_PROTOCOL
+		export USER
+		export PASSWORD
+		export OPENQRM_SERVER
+		export INTERFACE
+		export APPLIANCE_NAME
+		export OPENQRM_WEB_PROTOCOL
 		openqrm_integrate_local_server
 		;;
 
@@ -247,10 +247,10 @@ case "$1" in
 					;;
 				-p)
 					PASSWORD=$2
-					;;			
+					;;
 				-q)
 					OPENQRM_SERVER=$2
-					;;			
+					;;
 				-n)
 					APPLIANCE_NAME=$2
 					;;
@@ -276,13 +276,13 @@ case "$1" in
 			exit 1
 		fi
 		if [ "$OPENQRM_WEB_PROTOCOL" == "" ]; then
-            OPENQRM_WEB_PROTOCOL=http
+			OPENQRM_WEB_PROTOCOL=http
 		fi
-        export USER
-        export PASSWORD
-        export OPENQRM_SERVER
-        export APPLIANCE_NAME
-        export OPENQRM_WEB_PROTOCOL
+		export USER
+		export PASSWORD
+		export OPENQRM_SERVER
+		export APPLIANCE_NAME
+		export OPENQRM_WEB_PROTOCOL
 		openqrm_remove_local_server $USER $PASSWORD $OPENQRM_SERVER
 		;;
 
@@ -292,4 +292,3 @@ case "$1" in
 		;;
 
 esac
-		
diff --git a/trunk/src/plugins/local-storage/etc/init.d/local-storage b/trunk/src/plugins/local-storage/etc/init.d/local-storage
--- a/trunk/src/plugins/local-storage/etc/init.d/local-storage
+++ b/trunk/src/plugins/local-storage/etc/init.d/local-storage
@@ -30,82 +30,82 @@ export OPENQRM_SOURCE_DIR="$resource_basedir/openqrm/"
 DD_BLOCKSIZE=1024
 # define wget to use with https
 if [ "$openqrm_web_protocol" == "https" ]; then
-    WGET_NO_CERT_CHECK="--no-check-certificate"
+	WGET_NO_CERT_CHECK="--no-check-certificate"
 fi
 
 function local_storage_start() {
 	local_storage_stop 1>/dev/null 2>&1
 
-    # are we still on the initrd ?
-    # do not run on idle resources
-    if [ "$resource_image" == "idle" ] && [ -f /etc/initrd-devices.conf ]; then
-    	echo "Starting the openQRM local_storage-plugin (initrd)"
-        # check if we are at the end of a grab phase
-        if [ "$LOCAL_STORAGE_GRAB" != "" ]; then
-        	echo "local-storage: Detected 'after-grab' phase"
-            # send token to the openQRM server to remove the grab-appliance + resource capability
-            echo "local-storage: Sending 'after-grab' to the openQRM server"
-            if ! wget $WGET_NO_CERT_CHECK -q "$openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/local-storage-state.php?action=after-grab&token=$LOCAL_STORAGE_GRAB"; then
-                echo "local-storage: Error sending 'after-grab' to the openQRM server"
-                /bin/bash
-            fi
+	# are we still on the initrd ?
+	# do not run on idle resources
+	if [ "$resource_image" == "idle" ] && [ -f /etc/initrd-devices.conf ]; then
+		echo "Starting the openQRM local_storage-plugin (initrd)"
+		# check if we are at the end of a grab phase
+		if [ "$LOCAL_STORAGE_GRAB" != "" ]; then
+			echo "local-storage: Detected 'after-grab' phase"
+			# send token to the openQRM server to remove the grab-appliance + resource capability
+			echo "local-storage: Sending 'after-grab' to the openQRM server"
+			if ! wget $WGET_NO_CERT_CHECK -q "$openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/local-storage-state.php?action=after-grab&token=$LOCAL_STORAGE_GRAB"; then
+				echo "local-storage: Error sending 'after-grab' to the openQRM server"
+				/bin/bash
+			fi
 
-        elif [ "$LOCAL_STORAGE_DEPLOYMENT" != "" ]; then
-        	echo "local-storage: Detected 'after-deployment' phase"
-            if [ "$LOCAL_STORAGE_INAME" == "" ]; then
-                echo "local-storage: Could not find image-name. Exiting .."
-                exit 1
-            fi
-            # saving back the disk content
-            modprobe sunrpc 1>/dev/null 2>&1
-            modprobe lockd 1>/dev/null 2>&1
-            modprobe nfs 1>/dev/null 2>&1
-            modprobe ext3 1>/dev/null 2>&1
-            rm -rf /dev/null
-            mknod -m 666 /dev/null c 1 3
-            openqrm_portmap_start
+		elif [ "$LOCAL_STORAGE_DEPLOYMENT" != "" ]; then
+			echo "local-storage: Detected 'after-deployment' phase"
+			if [ "$LOCAL_STORAGE_INAME" == "" ]; then
+				echo "local-storage: Could not find image-name. Exiting .."
+				exit 1
+			fi
+			# saving back the disk content
+			modprobe sunrpc 1>/dev/null 2>&1
+			modprobe lockd 1>/dev/null 2>&1
+			modprobe nfs 1>/dev/null 2>&1
+			modprobe ext3 1>/dev/null 2>&1
+			rm -rf /dev/null
+			mknod -m 666 /dev/null c 1 3
+			openqrm_portmap_start
 
-            mkdir -p /mnt
-            if ! mount -t nfs -o rw,nolock $LOCAL_STORAGE_RESTORE /mnt; then
-                echo "ERROR: Could not mount $LOCAL_STORAGE_RESTORE by nfs"
-                # give a shell for the admin
-                /bin/bash
-            else
-                echo "local-storage: Mounted $LOCAL_STORAGE_RESTORE rw"
-            fi
+			mkdir -p /mnt
+			if ! mount -t nfs -o rw,nolock $LOCAL_STORAGE_RESTORE /mnt; then
+				echo "ERROR: Could not mount $LOCAL_STORAGE_RESTORE by nfs"
+				# give a shell for the admin
+				/bin/bash
+			else
+				echo "local-storage: Mounted $LOCAL_STORAGE_RESTORE rw"
+			fi
 
-            # grab
-            echo "local-storage: Starting grab-phase. Transfering disk-content to $LOCAL_STORAGE_INAME"
-            # grab all disks
-            for HARD_DISK in `cat /proc/partitions | grep -v major | sed -e '/^$/d' | awk {' print $4 '} | grep -v [0-9]`; do
-                echo "local-storage: Processing device /dev/$HARD_DISK"
-                INAME="/mnt/"$LOCAL_STORAGE_INAME"_x_"$HARD_DISK"_ping.img"
-                BSNAME="/mnt/"$LOCAL_STORAGE_INAME"_x_"$HARD_DISK"_bs.img"
-                rm -f $INAME
-                dd if=/dev/$HARD_DISK of=$INAME bs=$DD_BLOCKSIZE
-                # gzip is too slow
-                # nice -n 19 dd if=/dev/$HARD_DISK | gzip -9 > $INAME
-                echo "local-storage: Saving the MBR of /dev/$HARD_DISK"
-                dd if=/dev/$HARD_DISK of=$BSNAME bs=512 count=1
-                echo "local-storage: Cleaning device /dev/$HARD_DISK"
-                dd if=/dev/zero of=/dev/$HARD_DISK bs=$DD_BLOCKSIZE 2> /local-storage.err
-                rm -f /local-storage.err
-            done
-            echo "local-storage: Umounting image-store"
-            umount /mnt
+			# grab
+			echo "local-storage: Starting grab-phase. Transfering disk-content to $LOCAL_STORAGE_INAME"
+			# grab all disks
+			for HARD_DISK in `cat /proc/partitions | grep -v major | sed -e '/^$/d' | awk {' print $4 '} | grep -v [0-9]`; do
+				echo "local-storage: Processing device /dev/$HARD_DISK"
+				INAME="/mnt/"$LOCAL_STORAGE_INAME"_x_"$HARD_DISK"_ping.img"
+				BSNAME="/mnt/"$LOCAL_STORAGE_INAME"_x_"$HARD_DISK"_bs.img"
+				rm -f $INAME
+				dd if=/dev/$HARD_DISK of=$INAME bs=$DD_BLOCKSIZE
+				# gzip is too slow
+				# nice -n 19 dd if=/dev/$HARD_DISK | gzip -9 > $INAME
+				echo "local-storage: Saving the MBR of /dev/$HARD_DISK"
+				dd if=/dev/$HARD_DISK of=$BSNAME bs=512 count=1
+				echo "local-storage: Cleaning device /dev/$HARD_DISK"
+				dd if=/dev/zero of=/dev/$HARD_DISK bs=$DD_BLOCKSIZE 2> /local-storage.err
+				rm -f /local-storage.err
+			done
+			echo "local-storage: Umounting image-store"
+			umount /mnt
 
-            echo "local-storage: Sending 'finished-restore' to the openQRM server"
-            if ! wget $WGET_NO_CERT_CHECK -q "$openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/local-storage-state.php?action=finished-restore&token=$LOCAL_STORAGE_DEPLOYMENT"; then
-                echo "local-storage: Error sending 'finished-restore' to the openQRM server"
-                /bin/bash
-            fi
-        fi
+			echo "local-storage: Sending 'finished-restore' to the openQRM server"
+			if ! wget $WGET_NO_CERT_CHECK -q "$openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/local-storage-state.php?action=finished-restore&token=$LOCAL_STORAGE_DEPLOYMENT"; then
+				echo "local-storage: Error sending 'finished-restore' to the openQRM server"
+				/bin/bash
+			fi
+		fi
 
-    else
-        # we are in the reglar init phase
-        # nothing much to do yet
-    	echo "Starting the openQRM local_storage-plugin (regular init)"
-    fi
+	else
+		# we are in the reglar init phase
+		# nothing much to do yet
+		echo "Starting the openQRM local_storage-plugin (regular init)"
+	fi
 	return 0
 }
 
diff --git a/trunk/src/plugins/nagios3/bin/openqrm-nagios-manager b/trunk/src/plugins/nagios3/bin/openqrm-nagios-manager
--- a/trunk/src/plugins/nagios3/bin/openqrm-nagios-manager
+++ b/trunk/src/plugins/nagios3/bin/openqrm-nagios-manager
@@ -32,40 +32,129 @@ NAGIOS_GENERATED_CONF="$NAGIOS_CONF_DIR/openqrm-network.cfg"
 NAGIOS_CHECK_CMD=$1
 SUBNETFILE="/tmp/subnet.xml"
 CURRENTDIR=`pwd`
+
+OPENQRM_APPLIANCE_HOST_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/templates/openqrm_appliance_host.template"
+OPENQRM_APPLIANCE_SERVICE_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/templates/openqrm_appliance_service.template"
+OPENQRM_APPLIANCE_DEFAULT_SERVICE_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/templates/openqrm_appliance_default_service.template"
 export LANG=C
 
 
-# let only root run this script
-WHOAMI=`whoami`
-if [ "$WHOAMI" != "root" ]; then
-	echo "ERROR: Please run this script as root!"
-	exit 6
-fi
-
 if ! which screen 1>/dev/null; then
 	echo "ERROR: The 'screen' utility is not installed! Please install and try again."
-	image_shelf_log "ERROR: The 'screen' utility is not installed! Please install and try again."
+	nagios3_log "ERROR: The 'screen' utility is not installed! Please install and try again."
 	exit 6
 fi
 
 # re-run in background via screen
 if [ "$RUN_IN_BACKGROUND" != "true" ]; then
-    if [ -x /usr/bin/screen.real ]; then
-        RUNSCREEN="/usr/bin/screen.real"
-    else
-        RUNSCREEN=`which screen`
-    fi
-    export RUN_IN_BACKGROUND=true
-    SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
-    $RUNSCREEN -dmS $SCREEN_NAME $0 $@
-    exit
+	if [ -x /usr/bin/screen.real ]; then
+		RUNSCREEN="/usr/bin/screen.real"
+	else
+		RUNSCREEN=`which screen`
+	fi
+	export RUN_IN_BACKGROUND=true
+	SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
+	$RUNSCREEN -dmS $SCREEN_NAME $0 $@
+	exit
 fi
 
 # get the ip config
 openqrm_server_get_config
 export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
 
+# functions
 
+function nagios_manager_usage() {
+	echo "Usage: $0 [map|update_nagios]"
+	echo "       $0 automap -t <on|off>"
+	echo "       $0 add -n <appliance-name> -i <resource-ip> -p <service-ports-as-comma-separated-list>"
+	echo "       $0 remove_service -n <appliance-name> -p <service-ports-as-comma-separated-list>"
+	echo "       $0 remove_host -n <appliance-name>"
+	echo "       $0 event -n <appliance-name> -s <service-in-error> -m <event-message>"
+}
+
+function reload_cron() {
+	if [ -x /etc/init.d/cron ]; then
+		/etc/init.d/cron reload
+	elif [ -x /etc/init.d/crond ]; then
+		/etc/init.d/crond reload
+	else
+		echo "ERROR: Could not find cron init script in /etc/init.d/. Please reload cron manually!" | logger
+	fi
+}
+
+function reload_nagios() {
+	# quick hack to support icinga
+	if [ "$ICINGA_CONF_DIRECTORY" != "" ]; then
+		if [ -x /etc/init.d/nagios3 ]; then
+			/etc/init.d/icinga reload
+		fi
+	fi
+	if [ -x /etc/init.d/nagios3 ]; then
+		/etc/init.d/nagios3 restart
+	elif [ -x /etc/init.d/nagios ]; then
+		/etc/init.d/nagios restart
+	else
+		openqrm_post_event 0 "map" 3 "openqrm-nagios-manager" "Could not restart Nagios. Init script not found !."
+		echo "ERROR: Could not find nagios init script in /etc/init.d/. Please reload nagios manually!" | logger
+		return 1
+	fi
+}
+
+
+function get_service_by_port() {
+	F_SERVICE_PORT=$1
+	F_SERVICE_NAME=`grep "$F_SERVICE_PORT/tcp" /etc/services | awk '{ print $1":"$2}' | grep ":$F_SERVICE_PORT/tcp" | cut -d':' -f1 | head -n1`
+	if [ "$F_SERVICE_NAME" == "" ]; then
+		F_SERVICE_NAME="p$F_SERVICE_PORT"
+	fi
+	echo "$F_SERVICE_NAME"
+}
+
+
+# get parameters
+NAGIOS_CHECK_CMD=$1
+shift
+
+while [ $# -ne 0 ]; do
+	case "$1" in
+		-n)
+			APPLIANCE_NAME=$2
+			shift
+			;;
+		-i)
+			RESOURCE_IP=$2
+			shift
+			;;
+		-p)
+			SERVICE_PORT_LIST=$2
+			shift
+			;;
+		-t)
+			NAGIOS_AUTOMAP_TOGGLE=$2
+			shift
+			;;
+		-m)
+			NAGIOS_EVENT_MESSAGE=$2
+			shift
+			;;
+		-s)
+			NAGIOS_SERVICE_ERROR=$2
+			shift
+			;;
+		*)
+			echo "ERROR: Free commandline arguments are not allowed"
+			nagios_manager_usage
+			exit 6
+			;;
+	esac
+	shift
+done
+
+
+
+
+# main
 case "$NAGIOS_CHECK_CMD" in
 	map)
 		echo "Mapping the openQRM network"
@@ -73,7 +162,7 @@ case "$NAGIOS_CHECK_CMD" in
 		OPENQRM_NETWORK=`echo $OPENQRM_SERVER_IP_ADDRESS | cut -d'.' -f1-3`".*"
 		nagios_manager_lock aquire
 		openqrm_post_event 0 "map" 5 "openqrm-nagios-manager" "Starting to map the openQRM network!"
-		if ! nmap -sS -O -oX $SUBNETFILE $OPENQRM_NETWORK; then
+		if ! nmap --system-dns -sS -O -oX $SUBNETFILE $OPENQRM_NETWORK; then
 			nagios3_log openqrm-nagios-manager "ERROR while running nmap !"
 			nagios_manager_lock release
 			openqrm_post_event 0 "map" 3 "openqrm-nagios-manager" "Mapping the openQRM network failed!"
@@ -82,22 +171,18 @@ case "$NAGIOS_CHECK_CMD" in
 		openqrm_post_event 0 "map" 5 "openqrm-nagios-manager" "Mapping finished, generating the Nagios configuration!"
 		cd $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/bin
 		./nmap2nagios-ng.pl -i -d -r $SUBNETFILE -o $NAGIOS_GENERATED_CONF
-        # fix check_ping in generated config
-        sed -i -e "s#check_ping#check_ping!100.0,20%!500.0,60%#" $NAGIOS_GENERATED_CONF
-        # fix check_dig in generated config
-        sed -i -e "s#check_dig#check_dig!google.com#" $NAGIOS_GENERATED_CONF
+		# fix check_ping in generated config
+		sed -i -e "s#check_ping#check_ping!100.0,20%!500.0,60%#" $NAGIOS_GENERATED_CONF
+		# fix check_dig in generated config
+		sed -i -e "s#check_dig#check_dig!google.com#" $NAGIOS_GENERATED_CONF
 		cd $CURRENTDIR
-        # check if the new config is valid
+		# check if the new config is valid
 		if $NAGIOS_BINARY -v $NAGIOS_ETC_DIRECTORY/nagios.cfg; then
-			if [ -x /etc/init.d/nagios3 ]; then
-				/etc/init.d/nagios3 restart
-			elif [ -x /etc/init.d/nagios ]; then
-				/etc/init.d/nagios restart
-			else
-				nagios_manager_lock release
-				openqrm_post_event 0 "map" 3 "openqrm-nagios-manager" "Could not restart Nagios. Init script not found !."
-				exit 1
+			# quick hack to support icinga
+			if [ "$ICINGA_CONF_DIRECTORY" != "" ]; then
+				ln -sf $NAGIOS_GENERATED_CONF $ICINGA_CONF_DIRECTORY/openqrm-network.cfg
 			fi
+			reload_nagios
 			nagios_manager_lock release
 			openqrm_post_event 0 "map" 5 "openqrm-nagios-manager" "Automatic Nagios configuration finished successfully"
 		else
@@ -108,98 +193,135 @@ case "$NAGIOS_CHECK_CMD" in
 			exit 1
 		fi
 		;;
-	init)
-		echo "openqrm-nagios-manager->init"
-        if [ -f /etc/redhat-release ]; then
-            # make sure extra conf dir exist
-            if [ ! -d $NAGIOS_ETC_DIRECTORY/conf.d ]; then
-                mkdir -p $NAGIOS_ETC_DIRECTORY/conf.d
-            fi
-            if ! grep ^cfg_dir $NAGIOS_ETC_DIRECTORY/nagios.cfg | grep "conf.d"; then
-                echo "" >> $NAGIOS_ETC_DIRECTORY/nagios.cfg
-                echo "# added by openQRM" >> $NAGIOS_ETC_DIRECTORY/nagios.cfg
-                echo "cfg_dir=$NAGIOS_ETC_DIRECTORY/conf.d" >> $NAGIOS_ETC_DIRECTORY/nagios.cfg
-            fi
-
-            # on centos we have to check that check_dig + check_mysql are defined
-            # check_dig
-            if ! grep -r check_dig $NAGIOS_ETC_DIRECTORY/* 1>/dev/null; then
-                echo "-> Adding check_dig Nagios definition ..."
-                cp -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/templates/openqrm_check_dig.centos.template $NAGIOS_ETC_DIRECTORY/conf.d/openqrm_check_dig.cfg
-            fi
-            # check_myslq
-            if ! grep -r check_mysql $NAGIOS_ETC_DIRECTORY/* 1>/dev/null; then
-                echo "-> Adding check_mysql Nagios definition ..."
-                cp -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/templates/openqrm_check_mysql.centos.template $NAGIOS_ETC_DIRECTORY/conf.d/openqrm_check_mysql.cfg
-            fi
-
-        elif [ -f /etc/SuSE-release ]; then
-            NAGIOS3_PACKAGE_DEPENDENCIES=""
-			openqrm_post_event 0 "init" 5 "openqrm-nagios-manager" "Auto-setup of ndoutils is not supported for SUSE based distributions, skipping..."
-        fi
-
-        # linking the web dir
-        ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios3
-        # link the boot-service
-        ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/web/boot-service-nagios3.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-nagios3.tgz
-        # Nagios Single-Sign-On
-        # First backup original nagios.password
-        mv $NAGIOS_ETC_DIRECTORY/htpasswd.users $NAGIOS_ETC_DIRECTORY/htpasswd.users.bkp
-        # link openqrm .htaccess to nagios
-        ln -s $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd $NAGIOS_ETC_DIRECTORY/htpasswd.users
-        # First backup original nagios cgi.cfg
-        if [ ! -f $NAGIOS_ETC_DIRECTORY/cgi.cfg.bkp ]; then
-            cp -f $NAGIOS_ETC_DIRECTORY/cgi.cfg $NAGIOS_ETC_DIRECTORY/cgi.cfg.bkp
-        fi
-        # change nagiosadmin 2 openqrm for accessing nagios-gui
-        sed -i -e 's/nagiosadmin/openqrm/' $NAGIOS_ETC_DIRECTORY/cgi.cfg
-        # First backup original config.js
-        if [ ! -f /usr/share/nagios3/htdocs/config.js.bkp ]; then
-            cp -f /usr/share/nagios3/htdocs/config.js /usr/share/nagios3/htdocs/config.js.bkp
-        fi
-        # Fix WebGUI for Debian
-        sed -i "s/nagios\/cgi-bin/nagios3\/cgi-bin/g"  /usr/share/nagios3/htdocs/config.js
-        exit 0
-        ;;
 
 	automap)
 		echo "openqrm-nagios-manager->automap"
-        NAGIOS_AUTOMAP_TOGGLE=$2
-        case "$NAGIOS_AUTOMAP_TOGGLE" in
-            on)
-                # for the web-status
-                touch $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/web/.automap
-                # create cron job which will update the svn repo with files which were added by the web gui
-                cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/cron.d/openqrm-nagios3-automap.cron | \
-                    sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" > /etc/cron.d/openqrm-nagios3-automap
-                if [ -x /etc/init.d/cron ]; then
-                    /etc/init.d/cron reload
-                elif [ -x /etc/init.d/crond ]; then
-                    /etc/init.d/crond reload
-                else
-                    echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
-                fi
-    			openqrm_post_event 0 "automap" 5 "openqrm-nagios-manager" "Enabling auto-mapping of the openQRM-network"
-                ;;
+		case "$NAGIOS_AUTOMAP_TOGGLE" in
+			on)
+				# for the web-status
+				touch $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/web/.automap
+				# create cron job which will update the svn repo with files which were added by the web gui
+				cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/cron.d/openqrm-nagios3-automap.cron | \
+					sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" > /etc/cron.d/openqrm-nagios3-automap
+				reload_cron
+				openqrm_post_event 0 "automap" 5 "openqrm-nagios-manager" "Enabling auto-mapping of the openQRM-network"
+				;;
 
-            off)
-                rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/web/.automap
-                rm -f /etc/cron.d/openqrm-nagios3-automap
-                if [ -x /etc/init.d/cron ]; then
-                    /etc/init.d/cron reload
-                elif [ -x /etc/init.d/crond ]; then
-                    /etc/init.d/crond reload
-                else
-                    echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
-                fi
-                openqrm_post_event 0 "automap" 5 "openqrm-nagios-manager" "Disabling auto-mapping of the openQRM-network"
-                ;;
-        esac
-        exit 0
-        ;;
+			off)
+				rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/web/.automap
+				rm -f /etc/cron.d/openqrm-nagios3-automap
+				reload_cron
+				openqrm_post_event 0 "automap" 5 "openqrm-nagios-manager" "Disabling auto-mapping of the openQRM-network"
+				;;
+		esac
+		exit 0
+		;;
+
+	add)
+		SERVICE_PORT_LIST=`echo $SERVICE_PORT_LIST | sed -e "s/,/ /g"`
+		nagios_manager_lock aquire
+		# reset existing service for now
+		rm -f $NAGIOS_CONF_DIR/$APPLIANCE_NAME.*.service.config.cfg
+		for SERVICE_PORT in `echo $SERVICE_PORT_LIST`; do
+			SERVICE_NAME=`get_service_by_port $SERVICE_PORT`
+			echo "openqrm-nagios-manager->adding appliance $APPLIANCE_NAME/$RESOURCE_IP/$SERVICE_NAME/$SERVICE_PORT"
+			APPLIANCE_HOST_CONFIG="$NAGIOS_CONF_DIR/$APPLIANCE_NAME.host.cfg"
+			APPLIANCE_SERVICE_TEMPLATE="$NAGIOS_CONF_DIR/$APPLIANCE_NAME.service.template.cfg"
+			APPLIANCE_SERVICE_CONFIG="$NAGIOS_CONF_DIR/$APPLIANCE_NAME.$SERVICE_NAME.service.config.cfg"
+			# generate host
+			cat $OPENQRM_APPLIANCE_HOST_TEMPLATE | \
+				sed -e "s#@@APPLIANCE_NAME@@#$APPLIANCE_NAME#g" | \
+				sed -e "s#@@RESOURCE_IP@@#$RESOURCE_IP#g" \
+				> $APPLIANCE_HOST_CONFIG
+			# generate service default template
+			cat $OPENQRM_APPLIANCE_DEFAULT_SERVICE_TEMPLATE | \
+				sed -e "s#@@APPLIANCE_NAME@@#$APPLIANCE_NAME#g" \
+				> $APPLIANCE_SERVICE_TEMPLATE
+			# generate service config
+			cat $OPENQRM_APPLIANCE_SERVICE_TEMPLATE | \
+				sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | \
+				sed -e "s#@@APPLIANCE_NAME@@#$APPLIANCE_NAME#g" | \
+				sed -e "s#@@SERVICE_NAME@@#$SERVICE_NAME.$APPLIANCE_NAME#g" | \
+				sed -e "s#@@SERVICE_PORT@@#$SERVICE_PORT#g" \
+				> $APPLIANCE_SERVICE_CONFIG
+
+			# quick hack to support icinga
+			if [ "$ICINGA_CONF_DIRECTORY" != "" ]; then
+				ln -sf $APPLIANCE_HOST_CONFIG $ICINGA_CONF_DIRECTORY/$APPLIANCE_NAME.host.cfg
+				ln -sf $APPLIANCE_SERVICE_TEMPLATE $ICINGA_CONF_DIRECTORY/$APPLIANCE_NAME.service.template.cfg
+				ln -sf $APPLIANCE_SERVICE_CONFIG $ICINGA_CONF_DIRECTORY/$APPLIANCE_NAME.$SERVICE_NAME.service.config.cfg
+			fi
+
+			# check for each part of the configuration
+			if ! $NAGIOS_BINARY -v $NAGIOS_ETC_DIRECTORY/nagios.cfg; then
+				# remove completely
+				rm -f $NAGIOS_CONF_DIR/$APPLIANCE_NAME.*
+				# quick hack to support icinga
+				if [ "$ICINGA_CONF_DIRECTORY" != "" ]; then
+					rm -f $ICINGA_CONF_DIRECTORY/$APPLIANCE_NAME.*
+				fi
+				openqrm_post_event 0 "add" 2 "openqrm-nagios-manager" "Failed to add $SERVICE_NAME to $APPLIANCE_NAME! Reverting configuration ..."
+				break
+			fi
+
+		done
+
+		reload_nagios
+		nagios_manager_lock release
+		exit 0
+		;;
+
+	remove_host)
+		echo "openqrm-nagios-manager->removing appliance $APPLIANCE_NAME/$RESOURCE_IP"
+		# remove service config
+		nagios_manager_lock aquire
+		rm -f $NAGIOS_CONF_DIR/$APPLIANCE_NAME.*
+		# quick hack to support icinga
+		if [ "$ICINGA_CONF_DIRECTORY" != "" ]; then
+			rm -f $ICINGA_CONF_DIRECTORY/$APPLIANCE_NAME.*
+		fi
+		reload_nagios
+		nagios_manager_lock release
+		exit 0
+		;;
+
+	remove_service)
+		SERVICE_PORT_LIST=`echo $SERVICE_PORT_LIST | sed -e "s/,/ /g"`
+		nagios_manager_lock aquire
+		for SERVICE_PORT in `echo $SERVICE_PORT_LIST`; do
+			SERVICE_NAME=`get_service_by_port $SERVICE_PORT`
+			echo "openqrm-nagios-manager->removing $SERVICE_NAME/$SERVICE_PORT from appliance $APPLIANCE_NAME"
+			APPLIANCE_SERVICE_CONFIG="$NAGIOS_CONF_DIR/$APPLIANCE_NAME.$SERVICE_NAME.service.config.cfg"
+			# remove service config
+			rm -f $APPLIANCE_SERVICE_CONFIG
+			# quick hack to support icinga
+			if [ "$ICINGA_CONF_DIRECTORY" != "" ]; then
+				rm -f $ICINGA_CONF_DIRECTORY/$APPLIANCE_NAME.$SERVICE_NAME.service.config.cfg
+			fi
+		done
+		reload_nagios
+		nagios_manager_lock release
+		exit 0
+		;;
+
+	update_nagios)
+		echo "openqrm-nagios-manager->reloading nagios"
+		nagios_manager_lock aquire
+		reload_nagios
+		nagios_manager_lock release
+		exit 0
+		;;
+
+	event)
+		echo "openqrm-nagios-manager->event"
+		NAGIOS_SERVICE_ERROR=`echo $NAGIOS_SERVICE_ERROR | cut -d'.' -f1`
+		openqrm_post_event 0 "nagios" 2 "openqrm-nagios-manager" "Service $NAGIOS_SERVICE_ERROR on appliance $APPLIANCE_NAME in state : $NAGIOS_EVENT_MESSAGE"
+		exit 0
+		;;
+
+
 	*)
-		echo "Usage: $0 [map|init]"
-		echo "       $0 automap [on|off]"
+		nagios_manager_usage
 		exit 1
 		;;
 esac
diff --git a/trunk/src/plugins/puppet/etc/init.d/openqrm-plugin-puppet b/trunk/src/plugins/puppet/etc/init.d/openqrm-plugin-puppet
--- a/trunk/src/plugins/puppet/etc/init.d/openqrm-plugin-puppet
+++ b/trunk/src/plugins/puppet/etc/init.d/openqrm-plugin-puppet
@@ -28,7 +28,7 @@ openqrm_server_get_config
 export LANG=C
 # define wget to use with https
 if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
-    WGET_NO_CERT_CHECK="--no-check-certificate"
+	WGET_NO_CERT_CHECK="--no-check-certificate"
 fi
 
 
@@ -37,29 +37,29 @@ function openqrm_plugin_puppet_start() {
 	kill -9 `ps ax | grep puppetd | grep -v grep | awk {' print $1 '}` 2>/dev/null
 	openqrm_chkconfig del puppet
 	openqrm_chkconfig del puppetmaster
-    if which puppetmasterd 1>/dev/null 2>&1; then
-    	puppetmasterd -v -d -l syslog
-    else
-        echo "ERROR: Cloud not find puppetmasterd binary"
-    fi
-    if which puppetd 1>/dev/null 2>&1; then
-        puppetd -v -d -D -l syslog
-    else
-        echo "ERROR: Cloud not find puppetd binary"
-    fi
+	if which puppetmasterd 1>/dev/null 2>&1; then
+		puppetmasterd -v -d -l syslog
+	else
+		echo "ERROR: Cloud not find puppetmasterd binary"
+	fi
+	if which puppetd 1>/dev/null 2>&1; then
+		puppetd -v -d -D -l syslog
+	else
+		echo "ERROR: Cloud not find puppetd binary"
+	fi
 	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/puppet/.running
 }
 
 
 function openqrm_plugin_puppet_stop() {
 	echo "Stopping the openQRM puppet-plugin"
-    if [ -x "/etc/init.d/puppetmaster" ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d puppetmaster stop || exit $?
-        else
-            /etc/init.d/puppetmaster stop || exit $?
-        fi
-    fi
+	if [ -x "/etc/init.d/puppetmaster" ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d puppetmaster stop || exit $?
+		else
+			/etc/init.d/puppetmaster stop || exit $?
+		fi
+	fi
 	# be sure it is stopped
 	kill -9 `ps ax | grep puppetmaster | grep -v grep | awk {' print $1 '}` 2>/dev/null
 	kill -9 `ps ax | grep puppetd | grep -v grep | awk {' print $1 '}` 2>/dev/null
@@ -72,7 +72,7 @@ function openqrm_plugin_puppet_uninstall() {
 	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
 		echo -n "puppet: Please give a username to uninstall the plugin : "
 		read USERNAME
-		echo	
+		echo
 		echo -n "puppet: Please give the password for user $USERNAME : "
 		read PASSWORD
 		echo
@@ -82,21 +82,21 @@ function openqrm_plugin_puppet_uninstall() {
 
 	# remove from cron
 	rm -f /etc/cron.d/openqrm-puppetm-config
-    if [ -x "/etc/init.d/cron" ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d cron reload || exit $?
-        else
-            /etc/init.d/cron reload || exit $?
-        fi
-    elif [ -x /etc/init.d/crond ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d crond reload || exit $?
-        else
-            /etc/init.d/crond reload || exit $?
-        fi
-    else
-    	echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
-    fi
+	if [ -x "/etc/init.d/cron" ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d cron reload || exit $?
+		else
+			/etc/init.d/cron reload || exit $?
+		fi
+	elif [ -x /etc/init.d/crond ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d crond reload || exit $?
+		else
+			/etc/init.d/crond reload || exit $?
+		fi
+	else
+		echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
+	fi
 
 	# removing the puppet tables
 	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://localhost/openqrm/base/plugins/puppet/puppet-action.php?puppet_command=uninstall"; then
@@ -119,7 +119,7 @@ function openqrm_plugin_puppet_init() {
 	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
 		echo -n "puppet: Please give a username to init the plugin : "
 		read USERNAME
-		echo	
+		echo
 		echo -n "puppet: Please give the password for user $USERNAME : "
 		read PASSWORD
 		echo
@@ -140,13 +140,13 @@ function openqrm_plugin_puppet_init() {
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/puppet
 	# link the boot-service
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/web/boot-service-puppet.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-puppet.tgz
-	
+
 	# creating the tables
 	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://localhost/openqrm/base/plugins/puppet/puppet-action.php?puppet_command=init&puppet_domain=$OPENQRM_SERVER_DOMAIN"; then
 		puppet_manager_log init "ERROR: Could not create the puppet-plugin tables in the database!"
 		exit 1
 	fi
-	
+
 	# creating the svn dir at /etc/puppet to store the puppet configuration
 	# backup orgigin puppet dir first
 	if [ ! -d /etc/puppet.openqrm-puppet-plugin.bak ]; then
@@ -154,7 +154,7 @@ function openqrm_plugin_puppet_init() {
 	fi
 	# create the svn dir
 	rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/puppet
-    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/default/files
+	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/default/files
 	svnadmin create $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/puppet
 	svn import -q $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/default/ file://$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/puppet/ -m "initial import"
 	# and import to /etc/puppet
@@ -183,31 +183,31 @@ function openqrm_plugin_puppet_init() {
 	# create cron job which will update the svn repo with files which were added by the web gui
 	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/cron.d/openqrm-puppetm-config.cron | \
 		sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" > /etc/cron.d/openqrm-puppetm-config
-    if [ -x "/etc/init.d/cron" ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d cron reload || exit $?
-        else
-            /etc/init.d/cron reload || exit $?
-        fi
-    elif [ -x /etc/init.d/crond ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d crond reload || exit $?
-        else
-            /etc/init.d/crond reload || exit $?
-        fi
-    else
-    	echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
-    fi
+	if [ -x "/etc/init.d/cron" ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d cron reload || exit $?
+		else
+			/etc/init.d/cron reload || exit $?
+		fi
+	elif [ -x /etc/init.d/crond ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d crond reload || exit $?
+		else
+			/etc/init.d/crond reload || exit $?
+		fi
+	else
+		echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
+	fi
 	# create svn post-commit hook to immediately update the puppet configuration
 	cat $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/svn-hook/post-commit.tmpl | \
 		sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/puppet/hooks/post-commit
 	chmod 755 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/etc/puppet/hooks/post-commit
-	
+
 	# eventually clean up old ssl dir before starting
 	rm -rf /var/lib/puppet/ssl/*
 	rm -rf /var/lib/puppet/yaml/node/*
 	rm -rf /var/lib/puppet/yaml/facts/*
-	
+
 }
 
 
diff --git a/trunk/src/plugins/puppet/etc/init.d/puppet b/trunk/src/plugins/puppet/etc/init.d/puppet
--- a/trunk/src/plugins/puppet/etc/init.d/puppet
+++ b/trunk/src/plugins/puppet/etc/init.d/puppet
@@ -52,29 +52,29 @@ fi
 function puppet_start() {
 	echo "Starting the openQRM puppet-plugin"
 	puppet_stop 1>/dev/null 2>&1
-   	export FORCE_INSTALL=true
-   	openqrm_install_os_dependency puppet
+	export FORCE_INSTALL=true
+	openqrm_install_os_dependency puppet
 	# clean up eventual left-overs, be sure we get signed
 	rm -rf /etc/puppet/ssl/* /var/lib/puppet/ssl/* /var/lib/puppet/state/*
 	openqrm_chkconfig del puppet
 	puppet_stop 1>/dev/null 2>&1
-    if which puppetd 1>/dev/null 2>&1; then
-    	puppetd -v -d -D -l syslog
-    else
-        echo "ERROR: Cloud not find puppetd binary"
-    fi
+	if which puppetd 1>/dev/null 2>&1; then
+		puppetd -v -d -D -l syslog
+	else
+		echo "ERROR: Cloud not find puppetd binary"
+	fi
 }
 
 
 function puppet_stop() {
 	echo "Stopping the openQRM puppet-plugin"
-    if [ -x "/etc/init.d/puppet" ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d puppet stop || exit $?
-        else
-            /etc/init.d/puppet stop || exit $?
-        fi
-    fi
+	if [ -x "/etc/init.d/puppet" ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d puppet stop || exit $?
+		else
+			/etc/init.d/puppet stop || exit $?
+		fi
+	fi
 	kill -9 `ps ax | grep puppetd | grep -v grep | awk {' print $1 '}` 2>/dev/null
 }
 
diff --git a/trunk/src/plugins/sanboot-storage/bin/openqrm-sanboot-storage b/trunk/src/plugins/sanboot-storage/bin/openqrm-sanboot-storage
--- a/trunk/src/plugins/sanboot-storage/bin/openqrm-sanboot-storage
+++ b/trunk/src/plugins/sanboot-storage/bin/openqrm-sanboot-storage
@@ -33,19 +33,22 @@ elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
 	resource_id=0
 	resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
-    openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
+	openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
 fi
 export LANG=C
 LINEBR='
 '
 # define wget to use with https
 if [ "$openqrm_web_protocol" == "https" ]; then
-    WGET_NO_CERT_CHECK="--no-check-certificate"
+	WGET_NO_CERT_CHECK="--no-check-certificate"
 fi
 
 # using the resource_id as the shelf-id
 AOE_SHELF=$resource_id
 export AOE_SHELF
+# how long to wait for the volume authentication, each loop is 5 secs
+MAX_VOLUME_AUTHENTICATION_LOOP=30
+export MAX_VOLUME_AUTHENTICATION_LOOP
 
 # let only root run this script
 WHOAMI=`whoami`
@@ -177,7 +180,7 @@ fi
 case "$SANBOOT_COMMAND" in 
 
 	add)
-	
+
 		if [ "$SANBOOT_IMAGE_SIZE" == "" ]; then
 			SANBOOT_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
 			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
@@ -209,9 +212,12 @@ case "$SANBOOT_COMMAND" in
 		;;
 
 	remove)
-
+		# check that no snapshots existing with this volume as the origin
+		if lvs | awk '{ print $5 }' | grep -w $SANBOOT_IMAGE_NAME 1>/dev/null; then
+			openqrm_post_event 0 "remove" 3 "openqrm-sanboot-storage" "Snapshot exist from volume /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME. Not removing!"
+			exit 1
+		fi
 		echo -n "Removing logical volume $SANBOOT_IMAGE_NAME on volume group $SANBOOT_STORAGE_SERVER_VOLUME_GROUP"
-
 		if [ "$SANBOOT_IMAGE_TYPE" == "iscsi-san-deployment" ]; then
 			echo "Detected Iscsi-image. Removing from $IETDCONF"
 			check_iscsi_target
@@ -250,7 +256,7 @@ case "$SANBOOT_COMMAND" in
 			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
 		fi
 		export SANBOOT_IMAGE_SIZE
-		
+
 		# check that source fs-images exist
 		if ! `lvdisplay /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 1>/dev/null`; then
 			echo "ERROR: Could not find /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME on the storage-server"
@@ -282,16 +288,42 @@ case "$SANBOOT_COMMAND" in
 
 	auth)
 		echo "Authenticating $SANBOOT_IMAGE_TYPE image $SANBOOT_IMAGE_ROOTDEVICE to $SANBOOT_IMAGE_AUTH"
+		# this is just for starting auth, make sure the device is there, otherwise wait
+		SANBOOT_CHECK_VOLUME_GROUP=`echo $SANBOOT_IMAGE_ROOTDEVICE | cut -d':' -f1`
+		if [ "$SANBOOT_OPENQRM_USERNAME" != "" ] && [ "$SANBOOT_OPENQRM_PASSWORD" != "" ] && [ "$SANBOOT_IMAGE_NAME" != "" ]; then
+			MAX_AUTH_LOOP=0
+			while (true); do
+				if [ -e "/dev/$SANBOOT_CHECK_VOLUME_GROUP/$SANBOOT_IMAGE_NAME" ]; then
+					break
+				fi
+				sleep 5
+				if [ "$MAX_AUTH_LOOP" == "$MAX_VOLUME_AUTHENTICATION_LOOP" ]; then
+					sanboot_storage_log auth "ERROR: Volume $SANBOOT_IMAGE_TYPE image $SANBOOT_IMAGE_ROOTDEVICE / /dev/$SANBOOT_CHECK_VOLUME_GROUP/$SANBOOT_IMAGE_NAME does not exists, Cannot auth to $SANBOOT_IMAGE_AUTH"
+					exit 1
+				fi
+				MAX_AUTH_LOOP=$(( MAX_AUTH_LOOP + 1 ))
+			done
+		fi
+		export SANBOOT_IMAGE_ROOTDEVICE
 		if [ "$SANBOOT_IMAGE_TYPE" == "iscsi-san-deployment" ]; then
 			sanboot_storage_lock aquire
+			SANBOOT_IMAGE_ROOTDEVICE=`echo $SANBOOT_IMAGE_ROOTDEVICE | cut -d':' -f2`
 			manage_iscsi auth $SANBOOT_IMAGE_AUTH
 			sanboot_storage_lock release
 		elif [ "$SANBOOT_IMAGE_TYPE" == "aoe-san-deployment" ]; then
 			check_vblade
+			SANBOOT_IMAGE_ROOTDEVICE=`echo $SANBOOT_IMAGE_ROOTDEVICE | cut -d':' -f3`
 			sanboot_storage_lock aquire
 			manage_vblade auth $SANBOOT_IMAGE_AUTH
 			sanboot_storage_lock release
 		fi
+		# if we have an image name send back to openQRM that storage auth finished to remvoe the storage-auth-blocker
+		if [ "$SANBOOT_OPENQRM_USERNAME" != "" ] && [ "$SANBOOT_OPENQRM_PASSWORD" != "" ] && [ "$SANBOOT_IMAGE_NAME" != "" ]; then
+			if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$SANBOOT_OPENQRM_USERNAME --http-password=$SANBOOT_OPENQRM_PASSWORD "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/sanboot-storage/sanboot-storage-action.php?sanboot_storage_command=auth_finished&sanboot_image_name=$SANBOOT_IMAGE_NAME"; then
+				sanboot_storage_log auth "ERROR: Could not remove the storage-auth-blocker from the openQRM-server at $OPENQRM_SERVER_IP!"
+			fi
+		fi
+
 		;;
 
 	list)
@@ -301,7 +333,7 @@ case "$SANBOOT_COMMAND" in
 		echo "Posting current volume group status to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.vg.stat
 		vgs | grep -v VFree | sed -e "s/ \{1,\}//" > $STORAGE_STATUS_TMP
-        sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
+		sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$SANBOOT_OPENQRM_USERNAME --http-password=$SANBOOT_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/sanboot-storage/sanboot-storage-action.php?sanboot_storage_command=get_storage; then
 			echo "ERROR: Could not post the volume group status to the openQRM-server at $resource_openqrmserver!"
 			echo "ERROR: Could not post the volume group status to the openQRM-server at $resource_openqrmserver!" | logger
@@ -313,13 +345,13 @@ case "$SANBOOT_COMMAND" in
 		echo "Posting current $SANBOOT_IMAGE_TYPE logic volume status to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.$SANBOOT_STORAGE_SERVER_VOLUME_GROUP.lv.stat
 		> $STORAGE_STATUS_TMP
-        for LVOL in `lvs $SANBOOT_STORAGE_SERVER_VOLUME_GROUP | grep -v LSize | sed -e "s/ \{1,\}//" | awk {' print $1 '}`; do
+		for LVOL in `lvs $SANBOOT_STORAGE_SERVER_VOLUME_GROUP | grep -v LSize | sed -e "s/ \{1,\}//" | awk {' print $1 '}`; do
 			case $SANBOOT_IMAGE_TYPE in
 
 				iscsi-san-deployment)
 					if grep $LVOL $IETDCONF 1>/dev/null; then
 						lvs $SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$LVOL | grep -v LSize | sed -e "s/ \{1,\}//" >> $STORAGE_STATUS_TMP
-					fi					
+					fi
 					;;
 
 				aoe-san-deployment)
@@ -329,7 +361,7 @@ case "$SANBOOT_COMMAND" in
 					;;
 			esac
 		done
-        sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
+		sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$SANBOOT_OPENQRM_USERNAME --http-password=$SANBOOT_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/sanboot-storage/sanboot-storage-action.php?sanboot_storage_command=get_storage; then
 			echo "ERROR: Could not post the logic volume status to the openQRM-server at $resource_openqrmserver!"
 			echo "ERROR: Could not post the logic volume status to the openQRM-server at $resource_openqrmserver!" | logger
@@ -354,7 +386,7 @@ case "$SANBOOT_COMMAND" in
 						VOLUME_GROUP=`echo $LVOL | cut -d'/' -f3`
 						echo "$IMAGE_NAME,$VOLUME_GROUP:/dev/$TARGET/$LUN"
 						echo "$IMAGE_NAME,$VOLUME_GROUP:/dev/$TARGET/$LUN" >> $STORAGE_STATUS_TMP
-					fi					
+					fi
 					;;
 
 				aoe-san-deployment)
@@ -370,7 +402,7 @@ case "$SANBOOT_COMMAND" in
 					fi
 					;;
 			esac
-		
+
 		done
 
 		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$SANBOOT_OPENQRM_USERNAME --http-password=$SANBOOT_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/sanboot-storage/sanboot-storage-action.php?sanboot_storage_command=get_ident; then
@@ -389,15 +421,15 @@ case "$SANBOOT_COMMAND" in
 		fi
 		export SANBOOT_IMAGE_SIZE
 		echo "Resizing logical volume $SANBOOT_IMAGE_NAME + size $SANBOOT_IMAGE_SIZE MB using volume group $SANBOOT_STORAGE_SERVER_VOLUME_GROUP"
-        lvresize -L +$SANBOOT_IMAGE_SIZE /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
+		lvresize -L +$SANBOOT_IMAGE_SIZE /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
 
 		if [ "$SANBOOT_IMAGE_TYPE" == "iscsi-san-deployment" ]; then
 			echo "Detected Iscsi-image. Running resize2fs on /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME"
 			check_iscsi_target
 			sanboot_storage_lock aquire
 			manage_iscsi remove
-            e2fsck -f -y /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
-            resize2fs -fp /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
+			e2fsck -f -y /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
+			resize2fs -fp /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
 			manage_iscsi add snap $SANBOOT_IMAGE_AUTH
 			sanboot_storage_lock release
 		elif [ "$SANBOOT_IMAGE_TYPE" == "aoe-san-deployment" ]; then
@@ -405,8 +437,8 @@ case "$SANBOOT_COMMAND" in
 			check_vblade
 			sanboot_storage_lock aquire
 			manage_vblade remove
-            e2fsck -f -y /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
-            resize2fs -fp /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
+			e2fsck -f -y /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
+			resize2fs -fp /dev/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP/$SANBOOT_IMAGE_NAME 2>&1 | logger
 			manage_vblade add snap
 			sanboot_storage_lock release
 		fi
@@ -420,10 +452,10 @@ case "$SANBOOT_COMMAND" in
 
 
 	clone)
-        # cloning is similar to snapshots but since sanboot cannot (yet) create snapshots
-        # from snapshots we have to rsync the origin (which may be a snapshot) to a
-        # new lvol.
-        # .... good to have no partitions on the luns :) so we can mount them easily
+		# cloning is similar to snapshots but since sanboot cannot (yet) create snapshots
+		# from snapshots we have to rsync the origin (which may be a snapshot) to a
+		# new lvol.
+		# .... good to have no partitions on the luns :) so we can mount them easily
 		if [ "$SANBOOT_IMAGE_SNAPSHOT_NAME" == "" ]; then
 			echo "ERROR: Please give a name for the clone using the -s cmdline parmeter"
 			echo
@@ -436,41 +468,41 @@ case "$SANBOOT_COMMAND" in
 		export SANBOOT_IMAGE_SIZE
 		echo "Cloning logical volume $SANBOOT_IMAGE_NAME to $SANBOOT_IMAGE_SNAPSHOT_NAME size $SANBOOT_IMAGE_SIZE MB volume group $SANBOOT_STORAGE_SERVER_VOLUME_GROUP"
 
-        # re-run in background via screen
-        if [ "$RUN_IN_BACKGROUND" != "true" ]; then
-            if [ -x /usr/bin/screen.real ]; then
-                RUNSCREEN="/usr/bin/screen.real"
-            else
-                RUNSCREEN=`which screen`
-            fi
-            export RUN_IN_BACKGROUND=true
-            SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
-            $RUNSCREEN -dmS $SCREEN_NAME $FULL_COMMANDLINE
-            exit
-        fi
+		# re-run in background via screen
+		if [ "$RUN_IN_BACKGROUND" != "true" ]; then
+			if [ -x /usr/bin/screen.real ]; then
+				RUNSCREEN="/usr/bin/screen.real"
+			else
+				RUNSCREEN=`which screen`
+			fi
+			export RUN_IN_BACKGROUND=true
+			SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
+			$RUNSCREEN -dmS $SCREEN_NAME $FULL_COMMANDLINE
+			exit
+		fi
 
-        # create mountpoints for origin and clone
-        MOUNTPOINT_ORIGIN=`mktemp -d /tmp/$SANBOOT_IMAGE_NAME.origin.XXXXXXXXXX` || exit 1
-        MOUNTPOINT_CLONE=`mktemp -d /tmp/$SANBOOT_IMAGE_SNAPSHOT_NAME.clone.XXXXXXXXXX` || exit 1
+		# create mountpoints for origin and clone
+		MOUNTPOINT_ORIGIN=`mktemp -d /tmp/$SANBOOT_IMAGE_NAME.origin.XXXXXXXXXX` || exit 1
+		MOUNTPOINT_CLONE=`mktemp -d /tmp/$SANBOOT_IMAGE_SNAPSHOT_NAME.clone.XXXXXXXXXX` || exit 1
 
-        # create new volume
+		# create new volume
 		if ! lvcreate -L$SANBOOT_IMAGE_SIZE -n$SANBOOT_IMAGE_SNAPSHOT_NAME $SANBOOT_STORAGE_SERVER_VOLUME_GROUP; then
-            echo "ERROR: Could not create the new clone volume"
-            exit 1
-        fi
-        # create fs
-        if ! mkfs.ext3 -F /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME; then
-            echo "ERROR: Could not create the filesystem on /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME"
-            exit 1
-        fi
-        # mount clone
-        if ! mount /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME $MOUNTPOINT_CLONE; then
-            echo "ERROR: Could not mount clone /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME"
-            exit 1
-        fi
+			echo "ERROR: Could not create the new clone volume"
+			exit 1
+		fi
+		# create fs
+		if ! mkfs.ext3 -F /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME; then
+			echo "ERROR: Could not create the filesystem on /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME"
+			exit 1
+		fi
+		# mount clone
+		if ! mount /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME $MOUNTPOINT_CLONE; then
+			echo "ERROR: Could not mount clone /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_SNAPSHOT_NAME"
+			exit 1
+		fi
 
-        # remove origin from san/nas
-        export SANBOOT_IMAGE_NAME=$SANBOOT_IMAGE_NAME
+		# remove origin from san/nas
+		export SANBOOT_IMAGE_NAME=$SANBOOT_IMAGE_NAME
 		if [ "$SANBOOT_IMAGE_TYPE" == "iscsi-san-deployment" ]; then
 			check_iscsi_target
 			sanboot_storage_lock aquire
@@ -483,22 +515,22 @@ case "$SANBOOT_COMMAND" in
 			sanboot_storage_lock release
 		fi
 
-        # mount origin
-        if ! mount /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_NAME $MOUNTPOINT_ORIGIN; then
-            echo "ERROR: Could not mount origin /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_NAME"
-            exit 1
-        fi
+		# mount origin
+		if ! mount /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_NAME $MOUNTPOINT_ORIGIN; then
+			echo "ERROR: Could not mount origin /dev/mapper/$SANBOOT_STORAGE_SERVER_VOLUME_GROUP-$SANBOOT_IMAGE_NAME"
+			exit 1
+		fi
 
-        # rsync origin to clone
-        rsync -avz $MOUNTPOINT_ORIGIN/* $MOUNTPOINT_CLONE/
+		# rsync origin to clone
+		rsync -avz $MOUNTPOINT_ORIGIN/* $MOUNTPOINT_CLONE/
 
-        # umount origin + clone
-        umount $MOUNTPOINT_ORIGIN
-        umount $MOUNTPOINT_CLONE
-        rmdir $MOUNTPOINT_ORIGIN $MOUNTPOINT_CLONE
+		# umount origin + clone
+		umount $MOUNTPOINT_ORIGIN
+		umount $MOUNTPOINT_CLONE
+		rmdir $MOUNTPOINT_ORIGIN $MOUNTPOINT_CLONE
 
-        # add origin to san/nas
-        export SANBOOT_IMAGE_NAME=$SANBOOT_IMAGE_NAME
+		# add origin to san/nas
+		export SANBOOT_IMAGE_NAME=$SANBOOT_IMAGE_NAME
 		if [ "$SANBOOT_IMAGE_TYPE" == "iscsi-san-deployment" ]; then
 			check_iscsi_target
 			sanboot_storage_lock aquire
@@ -511,8 +543,8 @@ case "$SANBOOT_COMMAND" in
 			sanboot_storage_lock release
 		fi
 
-        # add clone to san/nas
-        export SANBOOT_IMAGE_NAME=$SANBOOT_IMAGE_SNAPSHOT_NAME
+		# add clone to san/nas
+		export SANBOOT_IMAGE_NAME=$SANBOOT_IMAGE_SNAPSHOT_NAME
 		if [ "$SANBOOT_IMAGE_TYPE" == "iscsi-san-deployment" ]; then
 			check_iscsi_target
 			sanboot_storage_lock aquire
@@ -525,17 +557,17 @@ case "$SANBOOT_COMMAND" in
 			sanboot_storage_lock release
 		fi
 
-        # here we notify openQRM that cloning has finished
+		# here we notify openQRM that cloning has finished
 		# in case we have a username + password post the updated list to the openQRM-server
-        # and notify openQRM that cloning has finished
+		# and notify openQRM that cloning has finished
 		if [ "$SANBOOT_OPENQRM_USERNAME" != "" ] && [ "$SANBOOT_OPENQRM_PASSWORD" != "" ]; then
-            CLONE_FINISHED="$SANBOOT_IMAGE_SNAPSHOT_NAME.clone"
-            touch $CLONE_FINISHED
-            if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$SANBOOT_OPENQRM_USERNAME --http-password=$SANBOOT_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $CLONE_FINISHED` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/sanboot-storage/sanboot-storage-action.php?sanboot_storage_command=clone_finished; then
-                echo "ERROR: Could not post clone-finished status to the openQRM-server at $resource_openqrmserver!"
-                echo "ERROR: Could not post clone-finished status to the openQRM-server at $resource_openqrmserver!" | logger
-            fi
-            # post lv
+			CLONE_FINISHED="$SANBOOT_IMAGE_SNAPSHOT_NAME.clone"
+			touch $CLONE_FINISHED
+			if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$SANBOOT_OPENQRM_USERNAME --http-password=$SANBOOT_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $CLONE_FINISHED` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/sanboot-storage/sanboot-storage-action.php?sanboot_storage_command=clone_finished; then
+				echo "ERROR: Could not post clone-finished status to the openQRM-server at $resource_openqrmserver!"
+				echo "ERROR: Could not post clone-finished status to the openQRM-server at $resource_openqrmserver!" | logger
+			fi
+			# post lv
 			$0 post_lv -u $SANBOOT_OPENQRM_USERNAME -p $SANBOOT_OPENQRM_PASSWORD -v $SANBOOT_STORAGE_SERVER_VOLUME_GROUP -t $SANBOOT_IMAGE_TYPE
 		fi
 
diff --git a/trunk/src/plugins/solx86/bin/openqrm-solx86 b/trunk/src/plugins/solx86/bin/openqrm-solx86
--- a/trunk/src/plugins/solx86/bin/openqrm-solx86
+++ b/trunk/src/plugins/solx86/bin/openqrm-solx86
@@ -28,33 +28,33 @@ export LC_ALL=C
 
 # are we root ?
 if ! id | grep root 1>/dev/null; then
-    echo "ERROR: Please run this util as root"
-    exit 1
+	echo "ERROR: Please run this util as root"
+	exit 1
 fi
 
 
 
 function usage() {
-        echo "Usage : $0 integrate -u <user> -p <password> -q <ip-address-of-openQRM-server> [-i <network-interface>]  [-s <http/https>]"
-        echo "        $0 remove -u <user> -p <password> -q <ip-address-of-openQRM-server>"
+		echo "Usage : $0 integrate -u <user> -p <password> -q <ip-address-of-openQRM-server> [-i <network-interface>]  [-s <http/https>]"
+		echo "        $0 remove -u <user> -p <password> -q <ip-address-of-openQRM-server>"
 }
 
 
 # function to check if required packages are installed
 function check_dependencies() {
-    IFS=':'
-    for PACKAGE in $SOLARIS_DEPENDENCIES; do
-            PBIN=`echo $PACKAGE | cut -d',' -f1`
-            PPGK=`echo $PACKAGE | cut -d',' -f2`
-            PREP=`echo $PACKAGE | cut -d',' -f3`
-            if ! which $PBIN 1>/dev/null 2>&1; then
-                    echo "NOTICE: The openQRM integration depends on the $PBIN util which is not installed!"
-                    echo "        Please install package $PPGK from the $PREP repository and try again."
-                    return 1
-            fi
-    done
-    IFS=$OLDIFS
-    return 0
+	IFS=':'
+	for PACKAGE in $SOLARIS_DEPENDENCIES; do
+			PBIN=`echo $PACKAGE | cut -d',' -f1`
+			PPGK=`echo $PACKAGE | cut -d',' -f2`
+			PREP=`echo $PACKAGE | cut -d',' -f3`
+			if ! which $PBIN 1>/dev/null 2>&1; then
+					echo "NOTICE: The openQRM integration depends on the $PBIN util which is not installed!"
+					echo "        Please install package $PPGK from the $PREP repository and try again."
+					return 1
+			fi
+	done
+	IFS=$OLDIFS
+	return 0
 }
 
 
@@ -105,29 +105,29 @@ function openqrm_integrate_solx86() {
 	local PASSWORD=$2
 	local OPENQRM_SERVER=$3
 	local INTERFACE=$4
-    local PROTOCOL=$5
+	local PROTOCOL=$5
 
-    echo "... checking dependecies"
-    if ! check_dependencies; then
-        return 1
-    fi
-    # do we have dropbear now ?
-    if ! which dropbear 1>/dev/null 2>&1; then
-        echo "ERROR: Please install dropbear server before integrating with openQRM"
-        return 1
-    else
-        DBSERVER=`which dropbear`
-    fi
-    if ! which dropbearkey 1>/dev/null 2>&1; then
-        echo "ERROR: Please install dropbearkey before integrating with openQRM"
-        return 1
-    else
-        DBKEY=`which dropbearkey`
-    fi
+	echo "... checking dependecies"
+	if ! check_dependencies; then
+		return 1
+	fi
+	# do we have dropbear now ?
+	if ! which dropbear 1>/dev/null 2>&1; then
+		echo "ERROR: Please install dropbear server before integrating with openQRM"
+		return 1
+	else
+		DBSERVER=`which dropbear`
+	fi
+	if ! which dropbearkey 1>/dev/null 2>&1; then
+		echo "ERROR: Please install dropbearkey before integrating with openQRM"
+		return 1
+	else
+		DBKEY=`which dropbearkey`
+	fi
 
 	echo "Integrating system to openQRM-server at $OPENQRM_SERVER"
 	mkdir -p `dirname $OPENQRM_RESOURCE_PARAMETER_FILE`
-	
+
 	if [ "$INTERFACE" == "" ]; then
 		echo "Which network-interface to use for the integration ?"
 		ifconfig -a | grep -v lo0 | grep UP | cut -d':' -f1 | uniq
@@ -142,36 +142,36 @@ function openqrm_integrate_solx86() {
 	local resource_id=-1
 	local resource_ip=`ifconfig $INTERFACE | grep inet | grep -v inet6 | awk {' print $2 '}`
 	local resource_mac=`ifconfig $INTERFACE | grep ether | awk {' print $2 '}`
-    # define wget to use with https
-    if [ "$PROTOCOL" == "https" ]; then
-        WGET_NO_CERT_CHECK="--no-check-certificate"
-    fi
+	# define wget to use with https
+	if [ "$PROTOCOL" == "https" ]; then
+		WGET_NO_CERT_CHECK="--no-check-certificate"
+	fi
 
 	# remove whitespaces
 	resource_mac=`fix_mac $resource_mac`
 	echo "Using $INTERFACE $resource_ip/$resource_mac"
-	
+
 	wget -q $WGET_NO_CERT_CHECK -O $OPENQRM_RESOURCE_PARAMETER_FILE "$PROTOCOL://$OPENQRM_SERVER/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
 	. $OPENQRM_RESOURCE_PARAMETER_FILE
-	
+
 	echo "Getting openqrm-client package"
-    mkdir -p $resource_basedir/openqrm/
+	mkdir -p $resource_basedir/openqrm/
 
 	cd $resource_basedir/openqrm/
 	wget -q $WGET_NO_CERT_CHECK "$PROTOCOL://$OPENQRM_SERVER/openqrm/boot-service/openqrm-client.solx86.tgz"
-    gunzip openqrm-client.solx86.tgz
+	gunzip openqrm-client.solx86.tgz
 	tar -xf openqrm-client.solx86.tar
 	rm -f openqrm-client.solx86.tar
 	export OPENQRM_SERVER_BASE_DIR=$resource_basedir
-    chmod +x $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86
-    chmod +x $resource_basedir/openqrm/sbin/*
-    chmod +x $resource_basedir/openqrm/bin/*
+	chmod +x $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86
+	chmod +x $resource_basedir/openqrm/sbin/*
+	chmod +x $resource_basedir/openqrm/bin/*
 
 	# gather some more details to create the appliance on the openQRM-server
 	solx86_root_device="local-disk"
 	solx86_root_device_type="zfs"
 	solx86_kernel_version="solaris-$resource_id"
-	
+
 	# now we send the local-integration signal to create
 	# the solx86 storage, image and appliance
 	if ! wget -O /dev/null -q $WGET_NO_CERT_CHECK --http-user=$USER --http-password=$PASSWORD "$PROTOCOL://$OPENQRM_SERVER/openqrm/base/plugins/solx86/solx86-action.php?solx86_command=integrate&solx86_id=$resource_id&solx86_root_device=$solx86_root_device&solx86_root_device_type=$solx86_root_device_type&solx86_kernel_version=$solx86_kernel_version"; then
@@ -182,40 +182,40 @@ function openqrm_integrate_solx86() {
 		return 1
 	fi
 
-    # here the system is integrated so far
-    # a resource, a kernel, an image, a (local) storage server and an appliance
-    # had been created. Now we need to start the remote-exec subsystem and the monitoring
-    ln -sf $DBSERVER $resource_basedir/openqrm/sbin/dropbear
-    ln -sf $DBKEY $resource_basedir/openqrm/bin/dropbearkey
-    # link the init script to rc.d 
+	# here the system is integrated so far
+	# a resource, a kernel, an image, a (local) storage server and an appliance
+	# had been created. Now we need to start the remote-exec subsystem and the monitoring
+	ln -sf $DBSERVER $resource_basedir/openqrm/sbin/dropbear
+	ln -sf $DBKEY $resource_basedir/openqrm/bin/dropbearkey
+	# link the init script to rc.d
 	ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/init.d/openqrm-client.solx86
-    ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/rc2.d/S99openqrm-client.solx86
-    ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/rc3.d/S99openqrm-client.solx86
-    ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/rcS.d/K99openqrm-client.solx86
+	ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/rc2.d/S99openqrm-client.solx86
+	ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/rc3.d/S99openqrm-client.solx86
+	ln -sf $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 /etc/rcS.d/K99openqrm-client.solx86
 
-    $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 start
+	$resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 start
 
-	
-	
+
+
 }
 
 function openqrm_remove_solx86() {
 	local USER=$1
 	local PASSWORD=$2
 	local OPENQRM_SERVER=$3
-    if [ ! -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
-    	echo "System already removed from openQRM-server at $OPENQRM_SERVER"
-        return 1
-    fi
+	if [ ! -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+		echo "System already removed from openQRM-server at $OPENQRM_SERVER"
+		return 1
+	fi
 	echo "Removing system from openQRM-server at $OPENQRM_SERVER"
 	. $OPENQRM_RESOURCE_PARAMETER_FILE
-    # define wget to use with https
-    if [ "$openqrm_web_protocol" == "https" ]; then
-        WGET_NO_CERT_CHECK="--no-check-certificate"
-    fi
+	# define wget to use with https
+	if [ "$openqrm_web_protocol" == "https" ]; then
+		WGET_NO_CERT_CHECK="--no-check-certificate"
+	fi
 
 
-    # stop the openqrm-client
+	# stop the openqrm-client
 	# try to remove components from the solx86 appliance
 	if ! wget -O /dev/null -q $WGET_NO_CERT_CHECK --http-user=$USER --http-password=$PASSWORD "$openqrm_web_protocol://$OPENQRM_SERVER/openqrm/base/plugins/solx86/solx86-action.php?solx86_command=remove&solx86_id=$resource_id"; then
 		echo "WARNING: Could not remove the appliance resource$resource_id from the openQRM-server!"
@@ -227,10 +227,10 @@ function openqrm_remove_solx86() {
 		return 1
 	fi
 
-    $resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 stop
+	$resource_basedir/openqrm/etc/init.d/openqrm-client.solx86 stop
 	rm -f $OPENQRM_RESOURCE_PARAMETER_FILE
 	rm -rf $resource_basedir/openqrm
-    # remove init scripts
+	# remove init scripts
 	rm -f /etc/init.d/openqrm-client.solx86 /etc/rc2.d/S99openqrm-client.solx86 /etc/rcS.d/K99openqrm-client.solx86
 	echo "Successfully removed system from openQRM"
 }
@@ -250,13 +250,13 @@ case "$1" in
 					;;
 				-p)
 					PASSWORD=$2
-					;;			
+					;;
 				-q)
 					OPENQRM_SERVER=$2
-					;;			
+					;;
 				-i)
 					INTERFACE=$2
-					;;			
+					;;
 				-s)
 					OPENQRM_WEB_PROTOCOL=$2
 					;;
@@ -279,7 +279,7 @@ case "$1" in
 			exit 1
 		fi
 		if [ "$OPENQRM_WEB_PROTOCOL" == "" ]; then
-            OPENQRM_WEB_PROTOCOL=http
+			OPENQRM_WEB_PROTOCOL=http
 		fi
 
 		openqrm_integrate_solx86 $USER $PASSWORD $OPENQRM_SERVER $INTERFACE $OPENQRM_WEB_PROTOCOL
@@ -298,10 +298,10 @@ case "$1" in
 					;;
 				-p)
 					PASSWORD=$2
-					;;			
+					;;
 				-q)
 					OPENQRM_SERVER=$2
-					;;			
+					;;
 			esac
 			shift
 		done
@@ -330,4 +330,3 @@ case "$1" in
 		;;
 
 esac
-		
diff --git a/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord b/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
--- a/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
+++ b/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
@@ -1,3 +1,4 @@
+#!/bin/sh
 # this is a very much stripped down openQRM monitor daemon
 #
 # This file is part of openQRM.
@@ -18,17 +19,16 @@
 #
 
 MONITOR_CMD=$1
-OPENQRM_SERVER_IP=$2
-ESX_SERVER_IP=$3
-USER=$4
-PASSWORD=$5
 MONITORD_LOCKFILE="/var/run/openqrm-vmware-esx-monitord"
 OPENQRM_RESOURCE_PARAMETER_FILE="/var/openqrm/openqrm-resource.conf"
 export LANG=C
-# define wget to use with https
-if [ "$openqrm_web_protocol" == "https" ]; then
-    WGET_NO_CERT_CHECK="--no-check-certificate"
+
+if [ ! -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+	echo "ERROR: Not initialyzed yet ! Please run :"
+	echo "  /bin/openqrm-start-vmware-esx-init <openqrm-server-ip-address> <esx-server-ip-address> <openqrm-user> <openqrm-password>"
+	exit 1
 fi
+. $OPENQRM_RESOURCE_PARAMETER_FILE
 
 # stop and exit
 if [ "$MONITOR_CMD" == "stop" ]; then
@@ -36,112 +36,44 @@ if [ "$MONITOR_CMD" == "stop" ]; then
 		kill `cat $MONITORD_LOCKFILE`
 		rm -f $MONITORD_LOCKFILE
 	fi
-    kill `ps -c | grep openqrm | grep -v grep | awk {' print $1 '}` 2>/dev/null
+	kill `ps -c | grep openqrm | grep vmware-esx | grep -v grep | awk {' print $1 '}` 2>/dev/null
 fi
-# not start ?
-if [ "$MONITOR_CMD" != "start" ]; then
-	echo "Usage : $0 start [openqrm-server-ip-address] [esx-server-ip-address] &"
-	echo "Usage : $0 stop"
-	exit 1
-fi
-# parameter check for start
-if [ "$OPENQRM_SERVER_IP" == "" ]; then
-	echo "Usage : $0 start [openqrm-server-ip-address] [esx-server-ip-address] &"
-	echo "Usage : $0 stop"
-	exit 1
-fi
-if [ "$ESX_SERVER_IP" == "" ]; then
-	echo "Usage : $0 start [openqrm-server-ip-address] [esx-server-ip-address] &"
-	echo "Usage : $0 stop"
-	exit 1
-fi
-
 
 # create lockfile
 if [ -f "$MONITORD_LOCKFILE" ]; then
-    kill `cat $MONITORD_LOCKFILE` 2>/dev/null
-    rm -f $MONITORD_LOCKFILE
-    kill `ps -c | grep openqrm | grep -v grep | awk {' print $1 '}` 2>/dev/null
+	kill `cat $MONITORD_LOCKFILE` 2>/dev/null
+	rm -f $MONITORD_LOCKFILE
+	kill `ps -c | grep openqrm | grep vmware-esx | grep -v grep | awk {' print $1 '}` 2>/dev/null
 fi
 echo "starting $0"
 echo $$ > $MONITORD_LOCKFILE
 
-
 # main
-
-# if we do not have a resource-parameter file yet we run integrate
-if [ ! -f "$OPENQRM_RESOURCE_PARAMETER_FILE" ]; then
-	mkdir -p `dirname $OPENQRM_RESOURCE_PARAMETER_FILE`
-	resource_id=-1
-	resource_ip="$ESX_SERVER_IP"
-	resource_mac=`vim-cmd hostsvc/net/config | grep -A5 "ipAddress" | grep -A5 $ESX_SERVER_IP | grep "mac " | cut -d'"' -f2`
-	# remove whitespaces
-	resource_mac=`echo $resource_mac`
-	echo "Using $resource_ip/$resource_mac"
-    # https will fail since busybox on the esx does not support https connections
-    # try http
-    wget -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
-    sleep 2
-    # check if http was successfull
-    if ! grep resource_openqrmserver $OPENQRM_RESOURCE_PARAMETER_FILE 1>/dev/null 2>&1; then
-        echo "ERROR: Could not integrate the VMware ESX server into the openQRM-server at $OPENQRM_SERVER_IP!"
-        rm -f $MONITORD_LOCKFILE
-        exit 1
-    fi
-	. $OPENQRM_RESOURCE_PARAMETER_FILE
-    # define wget to use with https
-    #if [ "$openqrm_web_protocol" == "https" ]; then
-    #    WGET_NO_CERT_CHECK="--no-check-certificate"
-    #fi
-    # https will fail since busybox on the esx does not support https connections
-    WGET_NO_CERT_CHECK=""
-    openqrm_web_protocol="http"
-
-	# gather some more details to create the appliance on the openQRM-server
-	local_server_root_device=`mount | grep ' / ' | awk {' print $1 '}`
-	local_server_root_device_type=`mount | grep ' / ' | awk {' print $5 '}`
-	local_server_kernel_version=`uname -r`
-
-	# now we integrate it via the local-sever plugin
-	if ! wget -O /dev/null $WGET_NO_CERT_CHECK -q "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/action/vmware-esx-integrate.php?USER=$USER&PASSWORD=$PASSWORD&local_server_command=integrate&local_server_id=$resource_id&local_server_root_device=$local_server_root_device&local_server_root_device_type=$local_server_root_device_type&local_server_kernel_version=$local_server_kernel_version"; then
-		echo "ERROR: Could not create the appliance resource$resouce_id on the openQRM-server!"
-		sleep 2
-		echo "NOTCIE: Removing the system from openQRM because of errors !"
-		# try to remove components from the local-server appliance
-		if ! wget -O /dev/null $WGET_NO_CERT_CHECK -q  "$openqrm_web_protocol://$OPENQRM_SERVER/openqrm/action/vmware-esx-integrate.php?USER=$USER&PASSWORD=$PASSWORD&local_server_command=remove&local_server_id=$resource_id"; then
-			echo "WARNING: Could not remove the appliance resource$resouce_id from the openQRM-server!"
-		fi
-		rm -f $MONITORD_LOCKFILE
-		exit 1
-	fi
-else
-	. $OPENQRM_RESOURCE_PARAMETER_FILE
-    # https will fail since busybox on the esx does not support https connections
-    WGET_NO_CERT_CHECK=""
-    openqrm_web_protocol="http"
-fi
+# https will fail since busybox on the esx does not support https connections
+WGET_NO_CERT_CHECK=""
+openqrm_web_protocol="http"
 
 # try to register all vms
 ESX_VER=$(vmware -v | awk '{print $4}')
 if [ -f /bin/vim-cmd ]; then
-    VMWARE_CMD=/bin/vim-cmd
+	VMWARE_CMD=/bin/vim-cmd
 elif [ -f /usr/bin/vmware-vim-cmd ]; then
-    VMWARE_CMD=/usr/bin/vmware-vim-cmd
+	VMWARE_CMD=/usr/bin/vmware-vim-cmd
 elif [[ "${ESX_VER}" == "3.0.3" ]] || [[ "${ESX_VER}" == "3.0.2" ]] || [[ "${ESX_VER}" == "3.0.1" ]] || [[ "${ESX_VER}" == "3.0.0" ]]; then
-    VMWARE_CMD=/usr/bin/vimsh
+	VMWARE_CMD=/usr/bin/vimsh
 else
-    echo "WARNING: Host type is not ESX 3.x+ or ESXi"
+	echo "WARNING: Host type is not ESX 3.x+ or ESXi"
 fi
 if [ "$VMWARE_CMD" != "" ]; then
-    for VM_CONF in `find /vmfs/volumes/ -name *.vmx`; do
-        echo "NOTICE: Trying to register $VM_CONF"
-        $VMWARE_CMD solo/registervm $VM_CONF
-    done
+	for VM_CONF in `find /vmfs/volumes/ -name *.vmx`; do
+		echo "NOTICE: Trying to register $VM_CONF"
+		$VMWARE_CMD solo/registervm $VM_CONF
+	done
 fi
 
 # loop
 HNAME=`hostname`
 while(true); do
-	wget -q -O /dev/null $WGET_NO_CERT_CHECK "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=update_info&resource_id=$resource_id&resource_hostname=$HNAME&resource_state=active&resource_event=statistics"
-	sleep 20
+	busybox wget -q -O /dev/null $WGET_NO_CERT_CHECK "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=update_info&resource_id=$resource_id&resource_hostname=$HNAME&resource_state=active&resource_event=statistics"
+	sleep 10
 done
diff --git a/trunk/src/plugins/xen-storage/etc/init.d/openqrm-plugin-xen-storage b/trunk/src/plugins/xen-storage/etc/init.d/openqrm-plugin-xen-storage
--- a/trunk/src/plugins/xen-storage/etc/init.d/openqrm-plugin-xen-storage
+++ b/trunk/src/plugins/xen-storage/etc/init.d/openqrm-plugin-xen-storage
@@ -24,8 +24,24 @@ OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $
 . $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/include/openqrm-plugin-xen-storage-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/etc/openqrm-plugin-xen-storage.conf
+openqrm_server_get_config
+OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
+# define wget to use with https
+if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
+	WGET="wget -q --no-check-certificate"
+else
+	WGET="wget -q"
+fi
+# which screen binary to use
+if [ -x /usr/bin/screen.real ]; then
+	RUNSCREEN="/usr/bin/screen.real"
+else
+	RUNSCREEN=`which screen`
+fi
+
 OPENQRM_VM_DIR="/var/lib/xen-storage/openqrm/"
 export OPENQRM_VM_DIR
+export resource_id=0
 
 
 LINE_IFS='
@@ -35,15 +51,55 @@ function openqrm_plugin_xen_storage_start() {
 	openqrm_plugin_xen_storage_stop 1>/dev/null 2>&1
 	echo "Starting the openQRM xen-storage-plugin"
 	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/xen-storage/.running
-    # start the vm status autostart
-    if [ -d "$OPENQRM_VM_DIR" ]; then
-        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart`; do
-            VM_NAME=`dirname $VM_CONFIG`
-            VM_NAME=`basename $VM_NAME`
-            echo "- auto-starting VM $VM_NAME"
-            $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/xen-storage/bin/openqrm-xen-storage-vm start -n $VM_NAME
-        done
-    fi
+	# start the vm status autostart
+	if [ -d "$OPENQRM_VM_DIR" ]; then
+		for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
+			VM_NAME=`dirname $VM_CONFIG`
+			VM_NAME=`basename $VM_NAME`
+			XEN_STORAGE_VM_MAC=`cat $OPENQRM_VM_DIR/$VM_NAME/mac1 2>/dev/null`
+			if [ "$XEN_STORAGE_VM_MAC" == "" ]; then
+				echo "- Could not find the MAC address of VM $VM_NAME, not autostarting..."
+				continue
+			fi
+			# already running ?
+			if ps ax | grep -i $XEN_STORAGE_VM_MAC | grep openqrm-xen-storage-monitord | grep -v grep 1>/dev/null; then
+				echo "- VM $VM_NAME already running, not autostarting..."
+				continue
+			fi
+
+			# ask openQRM what to do
+			if ! $WGET -O $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf "$OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$XEN_STORAGE_VM_MAC"; then
+				echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
+				continue
+			fi
+			unset appliance_state
+			unset image_rootdevice
+			. $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf
+			# is really active ?
+			if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
+				echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
+				lvchange -ay $image_rootdevice
+				sleep 2
+				# make sure the lvm device is active
+				if [ -e "$image_rootdevice" ]; then
+					echo "- auto-starting active VM $VM_NAME"
+					# make sure the rigth device is in the VM config
+					echo "phy:$image_rootdevice,hda,w" > $OPENQRM_VM_DIR/$VM_NAME/disk1
+					$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/bin/openqrm-xen-storage-vm start -n $VM_NAME
+				else
+					echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
+					continue
+				fi
+			else
+				# make sure the VM is not still attached to the disk
+				> $OPENQRM_VM_DIR/$VM_NAME/disk1
+				# start only the xen-storage monitor
+				echo "- auto-starting idle VM $VM_NAME"
+			fi
+			kill `ps ax | grep openqrm-xen-storage-monitord | grep -v grep | grep -i $XEN_STORAGE_VM_MAC | awk {' print $1 '}` 2>/dev/null
+			$RUNSCREEN -dmS $XEN_STORAGE_VM_MAC $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/sbin/openqrm-xen-storage-monitord $XEN_STORAGE_VM_MAC
+		done
+	fi
 
 }
 
@@ -59,7 +115,7 @@ function openqrm_plugin_xen_storage_uninstall() {
 	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
 		echo -n "xen-storage: Please give a username to uninstall the plugin : "
 		read USERNAME
-		echo	
+		echo
 		echo -n "xen-storage: Please give the password for user $USERNAME : "
 		read PASSWORD
 		echo
@@ -81,7 +137,7 @@ function openqrm_plugin_xen_storage_init() {
 	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
 		echo -n "xen-storage: Please give a username to init the plugin : "
 		read USERNAME
-		echo	
+		echo
 		echo -n "xen-storage: Please give the password for user $USERNAME : "
 		read PASSWORD
 		echo
@@ -97,15 +153,15 @@ function openqrm_plugin_xen_storage_init() {
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/boot-service-xen-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-xen-storage.tgz
 	# linking the image deployment parameters menu
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/image.xen-lvm-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.xen-lvm-deployment.php
-    # create storage dir for stat files
-    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/storage
-    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/storage
-    chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/bin/*
-    # create xen-stat dir
-    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/xen-stat
-    chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/xen-stat
+	# create storage dir for stat files
+	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/storage
+	chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/storage
+	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/bin/*
+	# create xen-stat dir
+	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/xen-stat
+	chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/web/xen-stat
 
-	
+
 }
 
 USER=$2
diff --git a/trunk/src/plugins/xen-storage/etc/init.d/xen-storage b/trunk/src/plugins/xen-storage/etc/init.d/xen-storage
--- a/trunk/src/plugins/xen-storage/etc/init.d/xen-storage
+++ b/trunk/src/plugins/xen-storage/etc/init.d/xen-storage
@@ -36,7 +36,18 @@ elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 fi
 OPENQRM_VM_DIR="/var/lib/xen-storage/openqrm/"
 export OPENQRM_VM_DIR
-
+# define wget to use with https
+if [ "$openqrm_web_protocol" == "https" ]; then
+	WGET="wget -q --no-check-certificate"
+else
+	WGET="wget -q"
+fi
+# which screen binary to use
+if [ -x /usr/bin/screen.real ]; then
+	RUNSCREEN="/usr/bin/screen.real"
+else
+	RUNSCREEN=`which screen`
+fi
 # do not start on the intitrd
 if [ -f /etc/initrd-devices.conf ]; then
 	exit 0
@@ -45,18 +56,60 @@ fi
 
 function xen_start() {
 	echo "Starting the openQRM xen-plugin"
-   	export FORCE_INSTALL=true
-   	openqrm_install_os_dependency screen
-    chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/bin/*
-    # start the vm status autostart
-    if [ -d "$OPENQRM_VM_DIR" ]; then
-        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart`; do
-            VM_NAME=`dirname $VM_CONFIG`
-            VM_NAME=`basename $VM_NAME`
-            echo "- auto-starting VM $VM_NAME"
-            $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/xen-storage/bin/openqrm-xen-storage-vm start -n $VM_NAME
-        done
-    fi
+	if which xm &>/dev/null; then
+		export FORCE_INSTALL=true
+		openqrm_install_os_dependency screen
+		chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/bin/*
+		# start the vm status autostart
+		if [ -d "$OPENQRM_VM_DIR" ]; then
+			for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart.$resource_id 2>/dev/null`; do
+				VM_NAME=`dirname $VM_CONFIG`
+				VM_NAME=`basename $VM_NAME`
+				XEN_STORAGE_VM_MAC=`cat $OPENQRM_VM_DIR/$VM_NAME/mac1 2>/dev/null`
+				if [ "$XEN_STORAGE_VM_MAC" == "" ]; then
+					echo "- Could not find the MAC address of VM $VM_NAME, not autostarting..."
+					continue
+				fi
+				# already running ?
+				if ps ax | grep -i $XEN_STORAGE_VM_MAC | grep openqrm-xen-storage-monitord | grep -v grep 1>/dev/null; then
+					echo "- VM $VM_NAME already running, not autostarting..."
+					continue
+				fi
+
+				# ask openQRM what to do
+				if ! $WGET -O $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$XEN_STORAGE_VM_MAC"; then
+					echo "- Could not get parameters for VM $VM_NAME, not auto-starting it ..."
+					continue
+				fi
+				unset appliance_state
+				unset image_rootdevice
+				. $OPENQRM_VM_DIR/$VM_NAME/resource-parameter.conf
+				# is really active ?
+				if [ "$appliance_state" == "active" ] && [ "$image_rootdevice" != "ram" ]; then
+					echo "- Activating Rootdevice $image_rootdevice for VM $VM_NAME"
+					lvchange -ay $image_rootdevice
+					sleep 2
+					# make sure the lvm device is active
+					if [ -e "$image_rootdevice" ]; then
+						echo "- auto-starting active VM $VM_NAME"
+						# make sure the rigth device is in the VM config
+						echo "phy:$image_rootdevice,hda,w" > $OPENQRM_VM_DIR/$VM_NAME/disk1
+						$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/bin/openqrm-xen-storage-vm start -n $VM_NAME
+					else
+						echo "- Rootdevice $image_rootdevice for VM $VM_NAME not existing, not autostarting it ..."
+						continue
+					fi
+				else
+					# make sure the VM is not still attached to the disk
+					> $OPENQRM_VM_DIR/$VM_NAME/disk1
+					# start only the xen-storage monitor
+					echo "- auto-starting idle VM $VM_NAME"
+				fi
+				kill `ps ax | grep openqrm-xen-storage-monitord | grep -v grep | grep -i $XEN_STORAGE_VM_MAC | awk {' print $1 '}` 2>/dev/null
+				$RUNSCREEN -dmS $XEN_STORAGE_VM_MAC $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen-storage/sbin/openqrm-xen-storage-monitord $XEN_STORAGE_VM_MAC
+			done
+		fi
+	fi
 
 }
 
diff --git a/trunk/src/plugins/zabbix/etc/init.d/zabbix b/trunk/src/plugins/zabbix/etc/init.d/zabbix
--- a/trunk/src/plugins/zabbix/etc/init.d/zabbix
+++ b/trunk/src/plugins/zabbix/etc/init.d/zabbix
@@ -38,32 +38,32 @@ fi
 function zabbix_start() {
 	echo "Starting the openQRM zabbix-plugin"
 	zabbix_stop 1>/dev/null 2>&1
-    # make sure we have the zabbix agent
-    if [ -f /etc/debian_version ]; then
-        apt-get update
-    fi
-   	export FORCE_INSTALL=true
-   	openqrm_install_os_dependency zabbix-agent
-    # set config
-    if [ -f /etc/zabbix/zabbix_agentd.conf ]; then
-    	echo "Setting configuration for the Zabbix-agent -> Zabbix-server $resource_openqrmserver"
-        sed -i -e "s/Server=.*/Server=$resource_openqrmserver/g" /etc/zabbix/zabbix_agentd.conf
-        # set hostname in agent conf
-        zabbix_client_hostname=`hostname`
-        sed -i -e "s/Hostname=.*/Hostname=$zabbix_client_hostname/g" /etc/zabbix/zabbix_agentd.conf
-    else
-    	echo "ERROR: Cloud find the Zabbix-agent configuration file!"
-    fi
-
-    # start agent
-    if [ -x "/etc/init.d/zabbix-agent" ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d zabbix-agent start || exit $?
-        else
-            /etc/init.d/zabbix-agent start || exit $?
-        fi
+	# make sure we have the zabbix agent
+	if [ -f /etc/debian_version ]; then
+		apt-get update
+	fi
+	export FORCE_INSTALL=true
+	openqrm_install_os_dependency zabbix-agent
+	# set config
+	if [ -f /etc/zabbix/zabbix_agentd.conf ]; then
+		echo "Setting configuration for the Zabbix-agent -> Zabbix-server $resource_openqrmserver"
+		sed -i -e "s/Server=.*/Server=$resource_openqrmserver/g" /etc/zabbix/zabbix_agentd.conf
+		# set hostname in agent conf
+		zabbix_client_hostname=`hostname`
+		sed -i -e "s/Hostname=.*/Hostname=$zabbix_client_hostname/g" /etc/zabbix/zabbix_agentd.conf
 	else
-    	echo "ERROR: Cloud not start the Zabbix-agent !"
+		echo "ERROR: Cloud find the Zabbix-agent configuration file!"
+	fi
+
+	# start agent
+	if [ -x "/etc/init.d/zabbix-agent" ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d zabbix-agent start || exit $?
+		else
+			/etc/init.d/zabbix-agent start || exit $?
+		fi
+	else
+		echo "ERROR: Cloud not start the Zabbix-agent !"
 	fi
 	return 0
 }
@@ -71,15 +71,15 @@ function zabbix_start() {
 
 function zabbix_stop() {
 	echo "Stopping the openQRM zabbix plugin"
-    # stop agent
-    if [ -x "/etc/init.d/zabbix-agent" ]; then
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d zabbix-agent stop || exit $?
-        else
-            /etc/init.d/zabbix-agent stop || exit $?
-        fi
+	# stop agent
+	if [ -x "/etc/init.d/zabbix-agent" ]; then
+		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d zabbix-agent stop || exit $?
+		else
+			/etc/init.d/zabbix-agent stop || exit $?
+		fi
 	else
-    	echo "ERROR: Cloud not stop the Zabbix-agent !"
+		echo "ERROR: Cloud not stop the Zabbix-agent !"
 	fi
 	return 0
 }
